### ISSUE TITLE
[Gebruikersgroepen] - Gastsprekers aanmeldformulier

### ISSUE THREAD

**Issue by conconnl** [stichtingjoomlanederland/joomlacommunity.nl#121]
De gastsprekers aanmeldformulier compleet maken, stijlen en doortesten.
- [x] Formulier compleet maken
- [x] Limiteren op maximaal 1 inzending
- [x] Username field tonen en klikbaar maken
- [ ] Tooltips toevoegen
- [ ] Lay-out testen en optimaliseren
- [ ] Mails configureren
- [ ] Fout en bedankt bericht configureren
- [ ] SEO configuratie

**Comment by conconnl** [comment]
Ik ga hiermee aan de slag

**Comment by n9iels** [comment]
Op zo een formulier lijkt mij handig:
- Naam, email etc
- Iets over jezelf
- Foto
- Regio (welke jug kun je heen)
- welk presentaties Geef je?
- Wat zijn je interesse gebieden (ala, kunnen we je vragen een prestatie te maken over...)

**Comment by jissereitsma** [comment]
Extra aanvulling:
- Social media links (twitter, Facebook, LinkedIn)
- Bedrijfsnaam en link

Misschien een koppeling met https://joind.in/ ?

**Comment by conconnl** [comment]
Alle genoemde opties zijn toegevoegd behalve joind.in
Ik zal dit tekstueel oplossen in het "Iets over jezelf" veld, mensen kunnen natuurlijk altijd nog wat andere websites benoemen

**Comment by conconnl** [comment]
Ik heb een optie in het formulier gebouwd, waarmee je het aantal inzendingen beperkt.
Dit is voor dit formulier, omdat een gastspreker zijn inzending kan aanpassen.
De melding moet alleen nog mooi gemaakt worden.

<img width="1019" alt="screen shot 2016-09-10 at 15 10 34" src="https://cloud.githubusercontent.com/assets/11913918/18410692/e4725356-7768-11e6-9585-805354a7df61.png">

**Comment by hvdmeer** [comment]
Wat is eigenlijk de status van dit?

**Comment by conconnl** [comment]
Ik zou zeggen sluiten. Dit was een actie vanuit de gebruikersgroepen en heb hier nooit meer wat over gehoord.
