### ISSUE TITLE
[Gebruikersgroepen] - Hoe begin ik een JUG tekst schrijven

### ISSUE THREAD

**Issue by conconnl** [stichtingjoomlanederland/joomlacommunity.nl#123]
Een pagina met informatie over het beginnen/hebben van een eigen JUG.

**Comment by conconnl** [comment]
@Stitch123

**Comment by superknutsel** [comment]
Edith heeft deze tekst, krijg haar alleen niet toegewezen... ?

**Comment by conconnl** [comment]
@superknutsel de tekst mag ook gemaild worden naar mij.

**Comment by conconnl** [comment]
> Tekst geschreven door Edith.

**Een nieuwe JUG starten?**
Ben je enthousiast geworden en vindt je geen JUG in de buurt ….wat nu? Een nieuwe JUG starten? Ja graag! Maar let op….neem dan wel even contact met mij op… er kunnen natuurlijk al ontwikkelingen in de buurt zijn waarvan je niets afweet. Er zijn ook enkele voorwaarden aan verbonden. De organisatie moet wel door minstens twee personen opgepakt worden, zodat er altijd iemand is om de avond te begeleiden. Een locatie is ook belangrijk en liever niet te dicht in de buurt van een al bestaande JUG of zelfs in dezelfde stad, dan zou je concurrent van elkaar kunnen zijn.

Hopelijk kunnen we je binnenkort begroeten bij een van de actieve JUG’s in Nederland of in België! Wees geen omstander maar een deelnemer!
 
**Don’t forget ! We are all Joomlers !**

Edith van Leeuwen
​Coördinator Nederlandstalige JUG's

------------
Persoonlijk vindt ik de tekst niet uitnodigend.
Ik ben zelf niet super goed in mooie Nederlandse teksten schrijven, dus hopelijk kan iemand anders dit doen.

**Comment by slibbe** [comment]
Ik kan wel wat veranderen naar eigen inzicht aan de tekst. Doen?

**Comment by conconnl** [comment]
@slibbe 
Michiel Verhoef is hier net aan begonnen, je kunt hem bereiken via Glip

**Comment by slibbe** [comment]
**Een nieuwe JUG starten?**
Ben je enthousiast geworden en vind je geen JUG in de buurt of op https://community.joomla.org/user-groups/66-netherlands.html, wat nu? Je begint gewoon een nieuwe JUG!
Neem eerst even contact op met Edit van Leeuwen, zij/hij coördineert alle JUG's in Nederland. Het kan natuurlijk zijn dat er nog iemand in jouw buurt bezig is met een JUG starten. Ook als je niet iemand kent om samen de JUG mee op te richten kan zij/hij je misschien helpen. Alleen de organisatie doen is namelijk niet handig; het is natuurlijk fijn als er altijd een organisator bij een JUG avond aanwezig kan zijn en als je samen kunt overleggen.
Wat betreft de locatie is het fijn als je niet vlakbij een andere JUG gaat zitten. Verder is het wenselijk als er in de buurt geparkeerd kan worden en je er met openbaar vervoer kunt komen en na afloop ook weer kunt vertrekken.

Hopelijk kunnen we je binnenkort begroeten als/bij een van de JUG’s in Nederland of in België! 

**Don’t forget ! We are all Joomlers !**

Edith van Leeuwen
​Coördinator Nederlandstalige JUG's

**Comment by hvdmeer** [comment]
Kan dit niet gewoon onderin het bestaande artikel "Algemene informatie Gebruikersgroepen" geplaatst worden? Dit in plaats van een nieuw/apart artikel?
http://nieuw.joomlacommunity.eu/bijeenkomsten

**Comment by Stitch123** [comment]
We kunnen het ook afvangen door gewoon naar mij te verwijzen als men een nieuwe JUG wil starten.
Men kan altijd informatie bij mij opvragen. Zo hou ik ook overzicht wat er zich eventueel voordoet in de groepen. En kan ik teleurstellingen voorkomen als een nieuwe groep te dicht op een bestaande zou komen. De tekst die ik ingestuurd heb heeft ook in het artikel gestaan over de Gebruikersgroepen in het Joomla handboek.

**Comment by hans2103** [comment]
@superknutsel wat is de status van dit issue?Kan het gesloten worden?

**Comment by superknutsel** [comment]
Aan de datum te zien zou ik het maar doen... Geloof dat de meeste mensen Edith of iemand anders wel weten te vinden.
