### ISSUE TITLE
[Development] - Google Map Component (René Kreijveld)

### ISSUE THREAD

**Issue by conconnl** [stichtingjoomlanederland/joomlacommunity.nl#135]
Tijdens JAB 2016 is er een begin gemaakt aan een component met een Google map waar alle JUGs opstaan.
Deze kan in Fase 2 geïmplementeerd worden.

**Comment by n9iels** [comment]
Dat klinkt best wel gaaf! Mocht daar hulp bij nodig zijn hoor ik het graag :-D

**Comment by sanderpotjer** [comment]
@conconnl het klopt dat daarvan nog geen code in de repository staat?

**Comment by conconnl** [comment]
Dat klopt.
@renekreijveld heeft een basis opgezet, zoals dit ook bij de joomla.org website is gedaan.
Wat de status is hiervan, is op dit moment bij mij niet bekend.
Is voor mij ook iets fancy dan noodzakelijk

**Comment by hvdmeer** [comment]
Is dit nog actueel met de huidige Google Maps API?

**Comment by renekreijveld** [comment]
Dit is sowieso niet actueel. Het proefconcept van destijds is nooit uitgewerkt omdat er toe geen behoefte aan was.

**Comment by conconnl** [comment]
Dan kunnen we hem sluiten. Als er behoefte was geweest dan was iemand er wel over begonnen.
