### ISSUE TITLE
Frontend com_rsevents beheer

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingjoomlanederland/joomlacommunity.nl#182]
Dit is voor nu uitgeschakeld omdat er veel schermen niet gestijled waren en ook niet werkte.

In Fase 2 inschakelen, testen & stijlen, maar dan alleen wat daadwerkelijk gebruikt gaat worden.

Wat mij betreft in eerste instantie
- event toevoegen/aanpassen
- locatie toevoegen/aanpassen
- bericht naar deelnemers

**Comment by hans2103** [comment]
Overleg met @hvdmeer geen frontend edit. Er is een hele mooie en met ACL in te richten Administrator hiervoor.
