### ISSUE TITLE
Boekenhoek vullen

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingjoomlanederland/joomlacommunity.nl#190]
@slibbe ik begreep dat jij eerder hebt aangegeven om de boekenhoek te willen vullen (http://nieuw.joomlacommunity.eu/aan-de-slag/boekenhoek) klopt dat inderdaad nog steeds?

**Comment by sanderpotjer** [comment]
Boekenhoek menu-item heb ik uitgezet zolang er geen content is. Verplaats dit issue naar volgende fase, geen blocking issue voor lancering nieuwe site.

**Comment by hvdmeer** [comment]
Misschien dat we ergens een overzicht kunnen creëren van boeken die gebruikt kunnen worden? Want ik neem aan dat er een soort van reviews gegeven worden van de huidige Joomla!boeken die op de markt zijn? Of heb ik dat mis?

**Comment by slibbe** [comment]
| Boek | Auteur | Beschikbaarheid | Kosten/Vorm | Taal |
|----------|-------------|-----------------|-------------------|--------|
| Joomla! 3 The book for everyone | Simon Grange | http://cinnk.com/en/joomla/3/the-book-for-everyone | online gratis/ eBook voor € 7,00 | Engels |
| JOOMLA 3 SEO & PERFORMANCE | Simon kloostra | https://joomlaseo.com/e-book-joomla-3-5-seo-performance | eBook voor € 6,50 | Engels |
| Programming Joomla Plugins | Jisse Reitsma | https://www.yireo.com/books/programming-joomla-plugins-book | paperback € 18,00 | Engels |

**Comment by MartijnMaandag** [comment]
In de huidige nieuwsberichten zitten een aantal boekbesprekingen:
https://www.joomlacommunity.nl/nieuws/algemeen/1016-joomla-seo
https://www.joomlacommunity.nl/nieuws/algemeen/980-boek-review-basiscursus-voor-joomla-3-herziene-editie

**Comment by slibbe** [comment]
https://www.joomlacommunity.nl/nieuws/algemeen/1016-joomla-seo is de Nederlandse editie van het engelstalige https://joomlaseo.com/e-book-joomla-3-5-seo-performance, beiden van Simon Kloostra.

Is het een idee om een soortgelijke lijst te maken zoals ook de Agenda er uit ziet, met de bespreking achter een "Lees meer.." ?

**Comment by hans2103** [comment]
overleg met @slibbe besloten hier momenteel geen aandacht aan te schenken.
issue gesloten
