### ISSUE TITLE
[Forum] Vertaling

### ISSUE THREAD

**Issue by marijkestuivenberg** [stichtingjoomlanederland/joomlacommunity.nl#201]
Beetje gekke vertaling in forum overview:

xxx reageerde **op** 6 minuten geleden.
Denk dat het woordje op hier weg moet
![recente berichten-joomlacommunity nl-forum](https://cloud.githubusercontent.com/assets/1097499/20775698/9455fa92-b75c-11e6-8a0f-583ad0bd2aca.png)

**Comment by hvdmeer** [comment]
Dat is vast een taalstring van EasyDiscuss. Misschien dat ik of Martijn dit nog snel kunnen aanpassen. 
En ik kan Martijn niet taggen, dus hopelijk leest hij Github nog snel, ik heb morgen pas tijd. Vandaag is totaal volgepland...

**Comment by marijkestuivenberg** [comment]
Heeft ook geen haast, ondertussen nog eentje gevonden die een beetje vreemd aandoet.
Wanneer je op de naam of profiel van een andere gebruiker klikt kun je hem/haar in het volgende scherm een PB sturen door op de twee spreekbubbels te klikken. In de pop-up staat dan staan "wegschrijven naar [naam gebruiker]" 
![pb-forum - joomlacommunity nl](https://cloud.githubusercontent.com/assets/1097499/20809097/3fc6fb30-b805-11e6-9597-2ef62e08de3f.png)
Ik stel voor "Persoonlijk bericht schrijven aan [naam gebruiker]"

**Comment by hvdmeer** [comment]
Het persoonlijke bericht heb ik op Transifex aangepast, maar de "reageerde op" krijg ik niet aangepast...

**Comment by MartijnMaandag** [comment]
'reageerde op' was een "reviewed" item. Dat kun je niet aanpassen. Ik heb een suggestie in Transifex toegevoegd, wat de volgende keer hopelijk door Stackideas wordt meegenomen en 'approved' wordt.

**Comment by conconnl** [comment]
Zie screenshot.
Denk dat er spaties achter de vertaling moeten.
![2017-01-02 15_26_39-nederlands joomla forum](https://cloud.githubusercontent.com/assets/11913918/21590926/0a2ee9ec-d100-11e6-9d32-a4fc0e395bc4.png)

**Comment by MartijnMaandag** [comment]
@conconnl Had ik ook al gezien, ook op andere plekken. Ga ik de komende tijd aanpassen en kijken hoe structureel dat, ook in het Engels bij EasyDiscuss, zit.

**Comment by MartijnMaandag** [comment]
Ik heb alle tot nu toe genoemde opmerkingen aangepast in de EasyDiscuss taalbestanden. Daarnaast heb ik ze in de overrides aangepast en een aantekening voor mijzelf gehouden zodat bij een volgende update van de taalbestanden vanuit Easydiscuss de overrides weer verwijderd kunnen worden.
Indien er nog meer taalkundige opmerkingen komen graag hier melden, dan zorg ik voor het aanpassen en bijhouden.

**Comment by sanderpotjer** [comment]
@MartijnMaandag dank!
