### ISSUE TITLE
Logo en banners pagina

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingjoomlanederland/joomlacommunity.nl#235]
Pagina maken met logo's en banners van JoomlaCommunity voor gebruik op de eigen site.

**Comment by hvdmeer** [comment]
En als ik mag aanvullen, graag ook voor het logo op Twitter en Facebook.

**Comment by hans2103** [comment]
Verwerken van de logos graag op https://github.com/stichtingjoomlanederland/media 
Daarnaast een pagina maken zoals https://www.byte.nl/logo

**Comment by hans2103** [comment]
@sanderpotjer kan jij mij een svg van het logo aanleveren?

**Comment by sanderpotjer** [comment]
Logo is toegezonden.

**Comment by hans2103** [comment]
vewerkt op https://github.com/stichtingjoomlanederland/media
wensen met betrekking tot creatie van nieuwe banners e.d. graag verwerken als issue op bovengenoemde repository
