### ISSUE TITLE
Bijeenkomst JUG aanmaken, wijzigen - Verslag JUG aanmaken, wijzigen

### ISSUE THREAD

**Issue by alex0703** [stichtingjoomlanederland/joomlacommunity.nl#244]
Ik zie niet hoe ik een bijeenkomst van JUG Utrecht op de Agenda kan plaatsen of wijzigen.
Hetzelfde geldt voor het maken en wijzigen van een verslag.
Nog niet mogelijk, of kijk ik niet goed?

**Comment by sanderpotjer** [comment]
@alex0703 de bedoeling is dat dit op de frontend mogelijk wordt, maar vanwege diverse issues staat dit nu nog uit.

Inloggen kan via de backend https://www.joomlacommunity.nl/administrator/
u: joomla
p: community

Daarna inloggen met je eigen gebruikersnaam en wachtwoord. Dan kan je de agenda aanpassen en bij de verslagen van je JUG.

**Comment by alex0703** [comment]
Zo te zien kan ik alleen bij Verslagen. Agenda zie ik niet.


Op 2 jan. 2017, om 14:19 heeft Sander Potjer <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@alex0703<https://github.com/alex0703> de bedoeling is dat dit op de frontend mogelijk wordt, maar vanwege diverse issues staat dit nu nog uit.

Inloggen kan via de backend https://www.joomlacommunity.nl/administrator/
u: joomla
p: community

Daarna inloggen met je eigen gebruikersnaam en wachtwoord. Dan kan je de agenda aanpassen en bij de verslagen van je JUG.

**Comment by sanderpotjer** [comment]
@alex0703 je zou ook onder Componenten bij RSEvents moeten kunnen

**Comment by alex0703** [comment]
Zijn er ook subfora voor gebrukersgroepen?

Op 2 jan. 2017, om 14:47 heeft Sander Potjer <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@alex0703<https://github.com/alex0703> je zou ook onder Componenten bij RSEvents moeten kunnen

**Comment by sanderpotjer** [comment]
@hvdmeer kan jij op de laatste vraag even reageren?

**Comment by hvdmeer** [comment]
@alex0703 Er is tijdens het algemeen  gebruikersgroepenoverleg afgelopen jaar bij Martijn thuis besloten dat er geen subfora voor de verschillende groepen komen. Dit omdat het deels wel erg stoffig was. (Lees, alleen maar erg oude topics) Wanneer alles in een subforum staat leeft het wellicht ook wat meer op het forum.

**Comment by alex0703** [comment]
Komt er dan 1 subforum voor alle jugs of geen apart subforum?

Verstuurd vanaf mijn iPhone

Op 2 jan. 2017 om 15:48 heeft Hans van der Meer <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@alex0703<https://github.com/alex0703> Er is tijdens het algemeen gebruikersgroepenoverleg afgelopen jaar bij Martijn thuis besloten dat er geen subfora voor de verschillende groepen komen. Dit omdat het deels wel erg stoffig was. (Lees, alleen maar erg oude topics) Wanneer alles in een subforum staat leeft het wellicht ook wat meer op het forum.

**Comment by sanderpotjer** [comment]
@alex0703 dat is er al: https://www.joomlacommunity.nl/forum/categories/joomlacommunity-nl/gebruikersgroepen-nederland-en-belgie

@hvdmeer wellicht nog wel even zichtbaarheid van alle categorieën nalopen, want deze is volgens mij niet voor publiek zichtbaar?

**Comment by hvdmeer** [comment]
Inderdaad ontbraken er een paar vinkjes, apart.
@alex0703 , kan je er nu wel bij komen?
@sanderpotjer , ik zal de overige categorieën ook even nalopen.

**Comment by alex0703** [comment]
Ja, maar alleen op de omslachtige manier dat ik eerst moet inloggen op de backend, dan inloggen met mijn eigen account en dan kan ik erbij. Niet handig / gebruikersvriendelijk.
Voorheen kon ik mijn verslagen en bijeenkomsten direct editen.
Die mogelijkheid lijkt nu niet aanwezig.

Groet,
Lex

Op 2 jan. 2017, om 18:07 heeft Hans van der Meer <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Inderdaad ontbraken er een paar vinkjes, apart.
@alex0703<https://github.com/alex0703> , kan je er nu wel bij komen?
@sanderpotjer<https://github.com/sanderpotjer> , ik zal de overige categorieën ook even nalopen.

**Comment by hvdmeer** [comment]
@alex0703 Jij hebt het nu over de agenda denk ik, zie de uitleg van Sander daarvoor: https://github.com/stichtingsympathy/joomlacommunity.nl/issues/244#issuecomment-269971523

Ik antwoordde op de vraag over het [forumgedeelte van de JUG's](https://www.joomlacommunity.nl/forum/categories/joomlacommunity-nl/gebruikersgroepen-nederland-en-belgie) waar je berichten kan plaatsen, dat dit nu één categorie is geworden.
Tenminste, dat denk ik.

**Comment by alex0703** [comment]
O, ja, loopt een beetje door mekaar... Forumgedeelte van de JUG's is nu te vinden.

**Comment by hans2103** [comment]
Zo te zien kan dit issue gesloten worden. Zo niet... graag een nieuw issue aanmaken.
