### ISSUE TITLE
Forum punten systeem uitschakelen

### ISSUE THREAD

**Issue by conconnl** [stichtingjoomlanederland/joomlacommunity.nl#248]
Ik wil voorstellen om het punten systeem in het voren uit te schakelen.
Dit bied in mijn ogen geen meerwaarde aan het geheel.

![2017-01-02 15_30_14-nederlands joomla forum](https://cloud.githubusercontent.com/assets/11913918/21590981/7670065e-d100-11e6-9cd0-e29a3886e47e.png)

![2017-01-02 15_30_41-nederlands joomla forum](https://cloud.githubusercontent.com/assets/11913918/21590982/7a769be6-d100-11e6-8bea-315394860e6a.png)

**Comment by hvdmeer** [comment]
Zit je nu mijn profiel uit te pluizen? 🤓
Ik zou het overigens aan laten, mensen zijn er gevoelig voor. Je krijgt de punten bij de onderwerpen. Ik weet even niet meer of je bepaalde punten weg kan laten zoals profiel updaten. Ik kan dat nu niet meer controleren.

**Comment by sanderpotjer** [comment]
Als we het aan laten staan moeten we wel een weergave hebben met de leden met de meeste punten, want anders trek je de mensen die er gevoelig voor zijn nog niet aan ;-)

**Comment by hvdmeer** [comment]
Oeh! 😃

**Comment by hans2103** [comment]
Punten zijn nu uitgeschakeld via Componenten > EasyDiscuss > Instellingen > Algemeen > Enable Points = No
