### ISSUE TITLE
Wijzigen Volledige naam / Roepnaam gaat  niet goed

### ISSUE THREAD

**Issue by renekreijveld** [stichtingjoomlanederland/joomlacommunity.nl#254]
Als je na inlog naar je profiel gaat, lukt het niet om voor de Volledige naam en Roepnaam twee verschillende dingen in te vullen. Het lijkt er op, dat wat je bij Roepnaam invult automatisch wordt overgenomen bij Volledige naam.

**Comment by conconnl** [comment]
Hoi Rene,

Dit had ik ook gemerkt, maar als je het dan in 2 stappen doet werkt het wel. 
Dacht dat het aan mij lag. 

Groeten
Wilco

**Comment by renekreijveld** [comment]
Hoe bedoel je in twee stappen ?

**Comment by renekreijveld** [comment]
Ik doe het volgende:

1. Vul bij Volledige naam in "René Kreijveld", Roepnaam laat ik leeg. Opslaan.
2. Dan staat bij Volledige naam én bij Roepnaam "René Kreijveld".
3. Verander bij Roepnaam "René Kreijveld" naar "René". Opslaan.
4. Dan staat bij Volledige naam én bij Roepnaam "René".

**Comment by conconnl** [comment]
Inderdaad, dat was mij nog niet eens opgevallen. 

Groeten
Wilco

**Comment by hans2103** [comment]
Door een update van EasyDiscuss is dit issue waarschijnlijk opgelost. 
Mocht het nog voordoen, dan graag die issue weer heropenen @conconnl @renekreijveld
