### ISSUE TITLE
Aanpassingen e-mailnotificatie forum

### ISSUE THREAD

**Issue by yolknet** [stichtingjoomlanederland/joomlacommunity.nl#255]
Als iemand reageert op een topic kun je een notificatie hiervan ontvangen.  Enkele suggesties om de mail te verbeteren (getest in Thunderbird):
- Logo vergroten
- De twee regels daarna kunnen weg, omdat je daarna hetzelfde meldt. Of de regels daarna weghalen en als tekst iets gebruiken als "Hallo, Er is gereageerd door XX op je bericht in het forum." Volgens mij hoeft het bericht niet langer te zijn?
- Letters van knop "Lees deze discussie" groter maken en de achtergrondkleur aanpassen aan een kleur van het logo.
- De afmeld-links ontbreken.
- Als ik de mail op mijn Samsung-telefoon lees dan is de tekst "Nieuwe reactie toegevoegd" van een prettige lettergrootte. De rest van het bericht is (te) klein.

**Comment by hans2103** [comment]
@yolknet speelt dit issue nog?
Zo ja... kun je een screenshot toevoegen van wat jij ziet?

**Comment by yolknet** [comment]
Ik weet niet of het nog speelt @hans2103 . Sluit het maar, ik denk het na 2 jaar inmiddels is opgelost of verbeterd.
