### ISSUE TITLE
[Forum] Onopgelost - Opgelost etc op mobiel valt over elkaar

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#257]
De selectiebalk Onopgelost - Opgelost etc valt op mobiele weergave over elkaar heen. 
![20170103_154052](https://cloud.githubusercontent.com/assets/7062995/21611062/8e8d9c1c-d1cb-11e6-91f9-2d91e3f7d131.png)

**Comment by hans2103** [comment]
<img width="408" alt="Schermafdruk 2019-05-17 12 02 05" src="https://user-images.githubusercontent.com/639822/57920556-9f562e00-789b-11e9-8f65-af03b2776898.png">

Het issue lijkt opgelost.... de weergave echter behoeft nog wel enige aandacht. Dat wordt opgepakt in issue #323
