### ISSUE TITLE
Inloggen redirect altijd naar forum

### ISSUE THREAD

**Issue by conconnl** [stichtingjoomlanederland/joomlacommunity.nl#258]
Als bijvoorbeeld op een pagina bent om je aan te melden voor een bijeenkomst, dan moet je natuurlijk eerst inloggen.
Het inloggen zorgt ervoor dat je doorgestuurd wordt naar het forum en dan moet je de bijeenkomst weer opzoeken.

Ik vindt dit erg gebruikersonvriendelijk.
Is dit aan te passen?

**Comment by sanderpotjer** [comment]
@conconnl en op welke plek log je dan uiteindelijk in? Via dropdown in menu?

**Comment by conconnl** [comment]
<img width="401" alt="screen shot 2017-01-04 at 21 21 23" src="https://cloud.githubusercontent.com/assets/11913918/21657711/dc50c8cc-d2c3-11e6-8efc-820672574e29.png">

**Comment by hans2103** [comment]
@conconnl 
Ik ben er mee eens dat redirect naar het forum niet zo prettig is. Tenminste... niet voor mij. 
De redirect naar blog na inloggen is een setting van de module mod_easydiscuss_welcome
Ik heb deze gewijzigd van `redirect to menu item forum` naar `stay on same page`
<img width="415" alt="Schermafdruk 2019-03-19 20 44 41" src="https://user-images.githubusercontent.com/639822/54636991-e1274b80-4a87-11e9-97ed-908398b106ba.png">

**Comment by conconnl** [comment]
Succesvol getest, ik blijf nu op dezelfde pagina.
