### ISSUE TITLE
Topics bewerken...?

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingjoomlanederland/joomlacommunity.nl#260]
@hvdmeer helaas heeft EasyDiscuss niet echt een versie archief voor topics. Maar zie bijv https://www.joomlacommunity.nl/forum/joomla/showcase/showcase-gasoline-directory-website waar de beste man zijn initiële topic en reacties heeft aangepast. 

Weet niet of dit wenselijk is eigenlijk. Volgens mij kunnen we nog niet instellen dat je X minuten kunt bewerken, maar neig er naar om de edit optie maar helemaal uit te zetten voor de default gebruiker. Wat jij?

**Comment by hvdmeer** [comment]
Mee eens en niet. Probleem Is dat als er nog geen preview mogelijk is dit kans geeft op vele foute posts die de gebruiker zelf niet kan wijzigen. 
Handiger zou zijn dat er net als wat we gewend waren er 5 min. edit mogelijkheid is. 

Maar als die preview er komt zou het geen probleem zijn. De aanvraag is gemaakt, kan jij niet even lief die kant uit kijken? 😇

**Comment by sanderpotjer** [comment]
Die feature request staat ook al uit: https://stackideas.com/voices/easydiscuss/item/990. Zal wel eens informeren...

**Comment by hvdmeer** [comment]
Is dit een combo issue voor het uit kunnen schakelen van het bewerken van eigen berichten door gebruikers èn voor het toevoegen van een preview mogelijkheid voor het daadwerkelijk posten? Zo niet, dan kan ik voor die laatste wel een nieuw issue aanmaken.

**Comment by hvdmeer** [comment]
Met #352 is dit issue ook afgehandeld.
