### ISSUE TITLE
[Forum] Afbeelding weergave

### ISSUE THREAD

**Issue by n9iels** [stichtingjoomlanederland/joomlacommunity.nl#264]
In dit topic wordt een hele breede afbeelding ingelanden:
https://www.joomlacommunity.nl/forum/joomla/overige-vragen/hulp-nodig-met-css

Deze valt echter uit de viewpoort, lijkt niet helemaal goed te gaan met verkleinen op viewpoort formaat

**Comment by hans2103** [comment]
Het issue doet zich nog steeds voor.
<img width="1190" alt="Schermafdruk 2019-05-17 12 10 51" src="https://user-images.githubusercontent.com/639822/57921089-d24cf180-789c-11e9-90b7-25948e582f19.png">

Oplossing:
```
#ed img {
   max-width: 100%;
}
```

**Comment by hans2103** [comment]
wijziging doorgevoerd
