### ISSUE TITLE
[mobiel] frontend inloggen

### ISSUE THREAD

**Issue by hans2103** [stichtingjoomlanederland/joomlacommunity.nl#267]
een JUG073 bezoeker liet me zien dat inloggen op JC.nl via mobiel niet gebruikersvriendelijk is. 
Het duurde even voordat hij door had dat je op het icoontje kunt klikken. Het duurde nog langer voordat hij door had dat je daarna naar beneden moest scrollen om bij het inlogscherm te komen. In zijn beleving niet echt gebruikersvriendelijk. (iphone 5)

 ![0](https://cloud.githubusercontent.com/assets/639822/21786795/1bdf9030-d6c6-11e6-90bb-d3792b769922.png)

**Comment by sanderpotjer** [comment]
En zijn suggestie om het beter te maken was....? Wat bedoel je overigens met "het icoontje kunt klikken"?

**Comment by hvdmeer** [comment]
Een hamburgermenu zou toch wel ingeburgerd moeten zijn, maar de optie "Login" staat wel erg onderin het scherm. Zou het een optie zijn om deze wat duidelijker boven in het mobiel menu te kunnen zetten?

**Comment by hans2103** [comment]
![Schermafdruk 2019-03-19 11 15 21](https://user-images.githubusercontent.com/639822/54598188-4ce1c800-4a38-11e9-8aa0-eb59a1f71db2.png)
