### ISSUE TITLE
[Forum] Rapporteer bericht functie 

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#268]
In EasyDiscuss is het mogelijk om een reactie/topic te rapporteren rapporteren wanneer deze niet volgens de regels is.

In de beheerszijde komt dit bericht aan, maar bij de eerste keer rapporteren heeft niemand daar bericht van gekregen. Bij:

> Instellingen - Algemeen - (tabblad) General Features
staat wel een opmerking dat er iets in de ACL geactiveerd moet worden. Ik kan dat nu niet inzien, misschien dat daar nog iets ingericht moet worden?

**Comment by Joomill** [comment]
Rapporteer functie lijkt niet te werken.
Zie laatste (spam)bericht op: https://www.joomlacommunity.nl/blogs/1493-de-grote-schoonmaak

**Comment by hans2103** [comment]
issue heropend omdat het rapporteren nog niet opgelost is. 
Issue wordt veroorzaakt door styling. 
Doordat de modal popup al bepaalde styling heeft, anders dan de styling van rscomments modal popup, wordt deze niet getoond.
door specifieke css te schrijven voor rscomments modal popup is het issue opgelost.

**Comment by hans2103** [comment]
@hvdmeer @MartijnMaandag Ik heb een comment gerapporteerd en ben benieuwd of jullie de melding daarvan ontvangen 
bij ontvangst mag dit issue gesloten worden.

**Comment by MartijnMaandag** [comment]
Ik krijg hem binnen.

**Comment by MartijnMaandag** [comment]
Ik geloof dat hij al gesloten is?

**Comment by hvdmeer** [comment]
Ik heb geen melding gezien. 😔

**Comment by MartijnMaandag** [comment]
Ik heb mezelf opgevoerd bij RSComments - Opties - Tabblad Lijst van reacties.
Hier staat onderaan: 
Lijst van E-mails,
Als je hierbij kunt kun je jezelf opvoeren, anders wil ik het wel doen.

**Comment by hvdmeer** [comment]
Gaarne, ik heb geen backend toegang tot RSComments

**Comment by MartijnMaandag** [comment]
Ik heb hanszit@gmail.com toegevoegd, zodat je ook een bericht krijgt als er een reactie wordt geplaatst. Ik heb ondervonden dat het wel handig is (spam en berichten dat er iets fout staat in een geplaatst artikel).
