### ISSUE TITLE
Geavanceerd zoeken op forum of website

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#270]
De zoekfunctie in de website zoekt op dit moment die de gehele website. Dus als je het forum wilt doorzoeken zie je ook hits van bv nieuwsberichten en andersom. 
Is het mogelijk dat et en geavanceerd zoeken komt waarbij je kan kiezen waarin je wilt zoeken? En bijvoorbeeld bij het forum ook alleen op de status Opgelost bijvoorbeeld

**Comment by hans2103** [comment]
ToDo:

- [ ] plaatsing checkboxen op https://www.joomlacommunity.nl/zoeken?q= om te zoeken in forum, blog, nieuws, agenda, gebruikersgroepen en downloads only.

**Comment by hans2103** [comment]
# zoekresultaat zonder filter
<img width="738" alt="Schermafdruk 2019-09-18 09 29 24" src="https://user-images.githubusercontent.com/639822/65126257-070db880-d9f7-11e9-8922-ee5fee16b745.png">

# zoekresultaat met filter
<img width="735" alt="Schermafdruk 2019-09-18 09 29 38" src="https://user-images.githubusercontent.com/639822/65126260-070db880-d9f7-11e9-8a6d-e3687e32655e.png">

**Comment by hvdmeer** [comment]
Ik heb gezocht in Chrome en als ik op https://www.joomlacommunity.nl/zoeken een zoekterm invul valt het zoekfilter onder de advertentie:
![zoeken-onder-reclame](https://user-images.githubusercontent.com/7062995/65140887-cd957700-da0f-11e9-9ba8-cd263b870b7a.png)

Voor de rest werkte het filter zoals ik verwachtte.

**Comment by hans2103** [comment]
Na test blijkt dat het niet onder de advertentie valt, maar verborgen wordt door een overflow hidden, die ik niet vinden kan. De dropdown wordt namelijk ook afgekapt zonder aanwezigheid van het formulier (zo blijkt uit een test).

Daarom een block toegevoegd, die verschijnt op moment er nog geen zoekopdracht gestart is, met het verzoek de zoekopdracht te starten. De dropdown zal dan geheel tonen. 

<img width="751" alt="Schermafdruk 2019-09-18 13 18 13" src="https://user-images.githubusercontent.com/639822/65144291-55cb4a80-da17-11e9-9160-5f4fea9d8a94.png">


Ik ben het er mee eens dat "Forum" stuk duidelijk is dan "EasyDiscuss"
Ik verplaats dat naar een nieuw issue, omdat het los staat van dit issue.

**Comment by hans2103** [comment]
@hvdmeer overflow hidden zat op `.content`
Volgens mij is die overbodig en heb ik verwijderd. 

Mocht ik nog iets voor je kunnen betekenen wat betreft dit issue, dan graag aan mij toewijzen

**Comment by hvdmeer** [comment]
Het werkt nu goed zover ik kan zien dus sluit ik deze.
