### ISSUE TITLE
[EasyDiscuss] Layout "Recent"- introductietekst

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#271]
Ik merk zelf dat mijn aandacht minder uit gaat naar het forum sinds de upgrade. 
Het zijn van die kleine dingen waar misschien wat meer tijd voor het wennen aan nodig is. Wat ik in ieder geval niet een meerwaarde vind hebben is de manier hoe omgegaan wordt met de introductietekst  in de Recent view op het forum

Wanneer je het topic voor het eerst in dit overzicht ziet staan zou je er wat aan kunnen hebben, maar bij elk nieuw bericht staat deze eerste 250 tekens van het eerste bericht er weer. 

Wat voor mij persoonlijk beter zou werken is een summier overzicht van alleen de topictitels, die kleine omschrijving voegt weinig toe, je klikt daardoor volgens mij niet sneller op een topic.

Instellingen van Recent view 
![recent-instellingen](https://cloud.githubusercontent.com/assets/7062995/22178164/bda9704e-e02f-11e6-9f52-61fc24ee71c1.jpg)
Recent view zonder introductietekst. Ik vind daar zelf veel te veel ruimte verspilt wordt aan niet interessante informatie of opvulling.
![recent-view](https://cloud.githubusercontent.com/assets/7062995/22178165/bdaabd3c-e02f-11e6-871d-43e1b481340e.jpg)

@sanderpotjer of @MartijnMaandag Wat vinden jullie?

**Comment by MartijnMaandag** [comment]
Ik ben het met je eens. Wat mij ook irriteert is dat de reacties steeds op "Oudste eerst" staan, terwijl ik liever "Laatste eerst" heb. Of kan ik dat zelf ergens instellen?
En er zijn er meer die het niet geweldig vinden (zie Arjan).

**Comment by hvdmeer** [comment]
Volgens mij is dat een profielmogelijkheid Martijn.
Over Arjan, dat is [dit topic](https://www.joomlacommunity.nl/forum/joomlacommunity-nl/over-joomlacommunity-nl/irritant-forum) (voor de duidelijkheid)

**Comment by hvdmeer** [comment]
Voorbeelden aanpassing:

- Vraagtype (Vraag/Tip etc) voor de topictitel ipv er onder.
- "Laatste activiteit" verwijderen (dit is de aanmaakdatum)
- "Rondeb reageerde 5 uur geleden" direct onder topictitel.

**Comment by hans2103** [comment]
Volstaat de volgende pagina @hvdmeer en @MartijnMaandag ?
https://www.joomlacommunity.nl/forum/recent

**Comment by MartijnMaandag** [comment]
@hans2103 Ik ben wel gewend aan zoals het er nu uitziet.

**Comment by hans2103** [comment]
@martijnmaandag
Jij went snel. Zoals het nu staat is een nieuwe situatie.
