### ISSUE TITLE
Koppeling JUG organisator naar Forumprofiel

### ISSUE THREAD

**Issue by Stitch123** [stichtingjoomlanederland/joomlacommunity.nl#275]
Op deze pagina - https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen - staan de organisatoren per JUG keurig vermeld.
Als je nu op een naam van de organisator klikt, spring je door naar het forum algemeen.
Ik wil deze graag aanpassen naar de bewuste forum-profielpagina, is dit mogelijk?
Of is er een betere suggestie?

**Comment by sanderpotjer** [comment]
@Stitch123 inloggen :-)

Als je ingelogd bent zou het wel moeten werken. Netter zou uiteraard een melding zijn "login om profiel te bekijken" maar weet niet of dat kan in easydiscuss

**Comment by Stitch123** [comment]
Hi @sanderpotjer 
Je hebt gelijk, als ik ben ingelogd dan doet ie dit wel. 
Ben het met je eens over de melding maar weet ook niet of dit mogelijk is.
Wellicht is het anders bij geen login logischer om door te linken naar de pagina van de desbetreffende JUG ipv het forum? Hiervan uit kan de bezoeker ook het emailadres van de JUG vinden om contact op te nemen. (even brainstormen sorry)

**Comment by sanderpotjer** [comment]
@Stitch123 op een JUG pagina is het mailadres ook niet te vinden volgens mij: https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/breda

**Comment by hvdmeer** [comment]
Ik krijg wel een alert te zien, maar dat hadden jullie vast ook @sanderpotjer @Stitch123 . ;)

> U moet ingelogd zijn om het profiel van een gebruiker te zien.

In ieder geval is er deze optie:

> Allow Public Guests To View User Profile
Dan kunnen gasten dus de profielen van alle gebruikers zien.

**Comment by Stitch123** [comment]
@sanderpotjer @hvdmeer Dat was me nog niet opgevallen maar het emailadres van de betreffende JUG moet toch wel bij de details vermeld worden.....is dit nog mogelijk?

En nee, het profiel van alle gebruikers moet wel afgeschermd blijven voor de privacy.  

Denk dat we een doorklik link moeten maken naar de pagina van de desbetreffende JUG ipv naar het forum. Zou dit kunnen? Zo niet dan moeten we de 'aanklikbaar' optie eraf halen....dit geeft zo alleen verwarring denk ik.

Nu worden het wel twee punten in 1 maar ik denk wel dat dit weer twee goede verbeteringen zijn! Dank!

**Comment by hvdmeer** [comment]
Ik zou de link willen behouden. De melding dat een gebruiker ingelogd moet zijn is aanwezig, maar valt wellicht wat minder op dat het verschijnen van het forum. 
Je hebt sowieso een registratie nodig om je aan te kunnen melden voor een bijeenkomst.

**Comment by hans2103** [comment]
Systeem doet wat het moet doen. Issue gesloten in overleg met @hvdmeer
