### ISSUE TITLE
[Forum] Afmeld-link in e-mail notificatie.

### ISSUE THREAD

**Issue by ghost** [stichtingjoomlanederland/joomlacommunity.nl#277]
Wij hebben gisteravond een mail ontvangen van iemand die zich van bepaalde e-mail notificaties afmelden wil.

In de notificatie mail is staat geen link vermeld om je af te melden. Momenteel moet je inloggen en via het menu bepaalde notificaties afmelden.

@hvdmeer weet jij of het mogelijk is deze link in de mail op te nemen?

Gr.
Marco

**Comment by hvdmeer** [comment]
Ik gooi het in mijn agenda om er naar te kijken, goede vraag.

**Comment by hvdmeer** [comment]
Hoi @SpiritJC , ik heb net in een mail naar mij toe gekeken en daar staat een afmeldlink onderin. Weet jij welk type email het betreft? 
![afmelden](https://cloud.githubusercontent.com/assets/7062995/23036996/18e1c466-f485-11e6-8ad8-acee7f3e36c2.png)

En waarom heeft degene het eigenlijk niet op het forum gevraagd? Dat kan daar ook prima. ;)

**Comment by SpiritJC** [comment]
Waarom diegene het niet op het forum heb gevraagd weet ik niet. Wat mij betreft maakt dat in dit geval ook niets uit.

Zie bijlage:

![mail](https://cloud.githubusercontent.com/assets/1671561/23057453/8b38c2ba-f4f0-11e6-8dbb-ad6e9c650863.JPG)

**Comment by SpiritJC** [comment]
Ik heb het getest, en inderdaad bij mij staat in dem ail gewoon een afmeld link.

**Comment by sanderpotjer** [comment]
@SpiritJC @hvdmeer wellicht ook even vanuit "gewone" gebruiker checken, niet dat wij dit toevallig wel zien omdat we admin zijn

**Comment by hvdmeer** [comment]
Ik kan inmiddels bevestigen dat het type Geregistreerd geen afmeldlink in de mail ziet staan. 
Misschien dat dit in EasyDiscuss in te stellen is. Ga ik naar kijken.

**Comment by hvdmeer** [comment]
Ik heb de toegangsrechten doorgenomen en wat andere instellingen binnen EasyDiscuss. Ik heb nergens iets gezien wat er voor zorgt dat Geregistreerden dit niet mogen zien. Mocht het ergens instelbaar zijn dan is het in de emailtemplate, alleen is dat code. 

@sanderpotjer , kan jij kijken of dit door ons aangepast kan worden of dat dit bij StackIdeas aangekaart moet worden? Oh, en proost! Of is de werkweek nog niet ten einde? ;)

**Comment by sanderpotjer** [comment]
@hvdmeer ik heb geen idee, dan zou ik er helemaal in moeten duiken. Wellicht gewoon even de. vraag op forum stackideas droppen

**Comment by hvdmeer** [comment]
Aangekaart: https://stackideas.com/forums/moderator-and-administrator-get-unsubscribe-link-in-mail-and-registrered-users-don-t

**Comment by hvdmeer** [comment]
Volgens hunnie zal het moeten werken. Of we onze credentials voor de site willen geven. Niet gedaan en doorgevraagd.

**Comment by GASOLINE** [comment]
@SpiritJC 
Jij vraagt: "Waarom diegene het niet op het forum heb gevraagd weet ik niet. Wat mij betreft maakt dat in dit geval ook niets uit."

Misschien om dat er op het forum staat:

"Je feedback is welkom via de GitHub issues op https://github.com/stichtingsympathy/joomlacommunity.nl/issues of in dit forum topic. Hartelijk dank!"

**Comment by hvdmeer** [comment]
Bedankt GASOLINE voor je screenshot, maakt het wel nog vreemder dat één gebruiker wel en een andere gebruiker blijkbaar die niet ziet in de mail.
