### ISSUE TITLE
[Form] Usability issues

### ISSUE THREAD

**Issue by n9iels** [stichtingjoomlanederland/joomlacommunity.nl#281]
Na het lezen van het feedback topic en zelf wat rond gekeken te hebben zie ik volgende mogelijke verbeterpunten:
- [ ] Pagination zowel onder als bovenaan een pagina
- [ ] Labels van gebruikers (Moderator, Beheers, Gebruikersgroep ...) kleiner lettertype
- [ ] Preview optie voor je bericht
- [ ] Ongelezen berichten weergave zoals bij het oude JC forum
- [ ] Mail notificaties alleen op de 1e reactie bij een nieuw bericht
  - [ ] Duidelijke in- en uitschrijf knoppen
- [ ] Experimenteren met een kleiner lettertype zodat alles wat 'compacter' wordt

**Comment by hvdmeer** [comment]
Waar gaan we met deze punten doen?

**Comment by hans2103** [comment]
in overleg met @hvdmeer gesloten.
