### ISSUE TITLE
beschikbaarheid uitgekleedde database dump voor thuisdev's

### ISSUE THREAD

**Issue by slibbe** [stichtingjoomlanederland/joomlacommunity.nl#282]
Er is helaas geen databasedump beschikbaar voor de thuis-ontwikkelaars die willen bijdragen aan de door-ontwikkeling van joomlacommunity.nl .

Zie ook bijgevoegde Glip-conversatie over dit onderwerp.
[glip-conversatie-databasedump.txt](https://github.com/stichtingsympathy/joomlacommunity.nl/files/853185/glip-conversatie-databasedump.txt)

**Comment by hans2103** [comment]
@slibbe zou jij een script kunnen maken om een uitgeklede dump te kunnen maken?
Ik lever op jouw verzoek een schema dump aan.

**Comment by hans2103** [comment]
@slibbes schema dump via de mail verzonden. Mag jij verder aan de slag met het maken van script om een uitgeklede db dump te kunnen maken
