### ISSUE TITLE
Automatisch sluiten topics werkt niet

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#286]
In EasyDiscus bij Instellingen - Algemeen - Composing (is een tab) kan er ingesteld worden dat een onderwerp automatisch op slot gezet wordt na een bepaald aantal dagen of een bepaald aantal dagen na de laatste reactie.

Het is een functie waar ik eerst mijn twijfels bij had maar er ook wel de nut van inzie. Tot nu toe werkt deze functie niet. Ik weet niet of dit aan onze kant ligt of aan StackIdeas, al zie ik daar op het forum er niemand over spreken. 

Kan iemand beoordelen of het probleem hier ligt of bij StackIdeas?

**Comment by MartijnMaandag** [comment]
Als ik het goed lees moet dan niet "Sluit nieuwe berichten automatisch" op "Nee" staan? (staat nu op Ja)

**Comment by hvdmeer** [comment]
Je kan wel eens gelijk hebben Martijn, ik heb de instelling aangepast.

**Comment by hans2103** [comment]
@hvdmeer is dit nog steeds een issue?

**Comment by hvdmeer** [comment]
Yep. Maar ik weet niet of dit een lokaal issue is of dat het aan de extensie ligt.

**Comment by hvdmeer** [comment]
Ik gooi nu handmatig de topics met de status Opgelost op slot na een paar dagen. Het zou wel handig zijn als dit via EasyDiscuss zelf kan gebeuren. Dus als iemand kan controleren waarom dit nu niet lukt, dan kunnen we daarna naar de oplossing toewerken. Scheelt mij ook weer regelmatig het forum afstromen alleen om topics op slot te gooien.

**Comment by hans2103** [comment]
@hvdmeer in de reactie van Martijn lees ik _Nieuwe berichten_
Zou dat dan betekenen dat nieuwe berichten, zonder reactie, automatisch na x dagen gesloten gaan worden?

Of wens je dat alle topics na x dagen zonder reactie gesloten worden?

**Comment by hvdmeer** [comment]
Uiteindelijk zal dat volgens mij op het zelfde neerkomen. Dat na bv. 30 dagen na laatste reactie (ook al is het de eerste) het topic gesloten wordt. Dit zijn de huidige instellingen die niet werken
![sluiten](https://user-images.githubusercontent.com/7062995/92360863-cb7b6b00-f0ed-11ea-9656-814a676ada89.png)

**Comment by hans2103** [comment]
issue aangemaakt bij StackIdeas => https://stackideas.com/forums/posting-automation-not-working-as-expected

**Comment by hvdmeer** [comment]
Ik zag er een antwoord bij staan en verwacht dat er een cron ingesteld moet worden. Ik heb het vinkje van automatisch sluiten uitgezet zodat ook oude berichten gesloten worden als het eenmaal werkt. :)

**Comment by hans2103** [comment]
reactie van de makers: 

> May i know do you have setup cronjob on your server yet?
> 
> Because this autolock feature can only be triggered when a Cronjob executes.
> 
> Once you setup cronjob on your site, you have to turn off this "Send email when the page loads" setting from backend > Easydiscuss > setting > notification so it will not affect on your site performance issue.

**Comment by hans2103** [comment]
Cron was voor Easydiscuss nog niet ingesteld. Nu wel. 
En de optie "Send email when the page loads" is nu uitgeschakeld

**Comment by hans2103** [comment]
@hvdmeer zou jij in de gaten kunnen houden of deze wijziging succesvol is? Indien er nog problemen voordoen, dan issue weer aan mij toewijzen. Anders mag het gesloten worden.

**Comment by hvdmeer** [comment]
Ik kreeg net wel een mail met alle onderwerpen "terwijl ik weg was".

**Comment by hans2103** [comment]
> Ik kreeg net wel een mail met alle onderwerpen "terwijl ik weg was".

is dat goed?

**Comment by hvdmeer** [comment]
Bij Instellingen - Notificaties heb ik de onderstaande switch uitegeschakeld. In de mail die gestuurd wordt zaten ook e-mailadressen. In ieder geval in de versie die ik ontvangen heb, Mochten we via mail een verzameling van topics per week (of ander interval) willen versturen dan zal die mailtemplate aangepast moeten worden.

![emaildigest](https://user-images.githubusercontent.com/7062995/92683262-bba09880-f332-11ea-9c5f-74ba563dc442.png)


Verder zitten nu alle niet recente topics op het forum op slot, de gewenste functie werkt dus nu zoals verwacht en daarom kan deze issue gesloten worden.
