### ISSUE TITLE
Filter op tekst aanpassen

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#311]
Er is een gebruiker die het onderstaande in een [ code ] - markup wilde laten tonen, dit wordt alleen weggefilterd. Ik zie zelf niet wat hier de schadelijke trefwoorden zijn. Dus is het mogelijk om hier even naar te kijken?
`RewriteCond %{HTTPS} off
RewriteRule ^(.*) https://nieuwsberichten.eu%{HTTP_HOST}%{REQUEST_URI}[R=301,L]`

**Comment by sanderpotjer** [comment]
@hvdmeer dit ging dan om post op forum?

**Comment by hvdmeer** [comment]
Klopt. Had duidelijker geweest als ik dat er bij had gezet.
