### ISSUE TITLE
Automatisch bepaalde categorieën delen via social media

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingjoomlanederland/joomlacommunity.nl#313]
aangevuld door @hans2103 
- [ ] auto berichtgeving naar Twitter
- [ ] auto berichtgeving naar Facebook

**Comment by hans2103** [comment]
Middels [Feedburner](https://feedburner.google.com) is auto tweet mogelijk.
Lijkt me een goede om die alvast in te zetten.

@hvdmeer Feedburner wordt gevoed via RSS. Ik kan deze voor JoomlaCommunity opzetten. Daarvoor zou ik graag van je willen weten welke content er in de feed moet komen te staan.

**Comment by hans2103** [comment]
@hvdmeer ook al gekeken naar IFTTT?

**Comment by hvdmeer** [comment]
Ik zie wel een IFTTT applet, maar dan moet je natuurlijk in die applet de autorisatie van FB en TW geven. Ik weet niet of dat een dingetje is. Ik heb zelf als test een RSS to mail ingesteld, dat werkt.
https://ifttt.com/applets/hPdYr2CX-post-rss-feed-to-facebookpage-twitter
Ik heb alleen niet zo snel een LinkedIn groep-optie kunnen vinden.

Over AutoTweetNG Free van Extly. De gratis versie lijkt te kunnen voldoen voor FB en TW.  Deze is gelimiteerd tot het gebruik van 2 RSS feeds en 2 Social Media channels om te plaatsen. Dan missen we één kanaal die we gebruiken. (Ik ben druk bezig ook alles in de LinkedIn groep te plaatsen)

De betaalde versie heeft ook een EasyDiscuss plugin, mocht het interessant zijn om topics te delen.
De RSEvents Post template die in de Pro zit zegt me even 1-2-3 niks.

De gratis versie van Hootsuite kan dire Social Media kanalen aan, dat zou wellicht ook een mogelijkheid kunnen zijn.

**Comment by hans2103** [comment]
@hvdmeer ik maak veelvuldig gebruik van IFTTT. Fijne tool... als je daarmee vooruit kunt zou fijn zijn. 
Dan kunnen we gebruik maken van de standaard RSS feed van Joomla en hoeven we verder geen 3th party extensies te installeren op de site. 
Mee eens? Pak jij dit verder op?

**Comment by hans2103** [comment]
@hvdmeer ben jij hiermee nog verder gekomen?

**Comment by hvdmeer** [comment]
Op dit moment krijg ik netjes een mail binnen als er iets gepost is. Ik ben er niet mee verder gegaan qua automatiseren omdat ik regelmatig problematische titels zie en daarnaast ik van mening ben dat er toch wel iets omschreven moet worden in het bericht. Dat lijkt me niet vanuit het automatisch plaatsen via IFTTT kunnen. 

Bijvoorbeeld "Er is een nieuw verslag van" $categorienaam. $artikeltitel. Dat zou voor mij toch minimaal moeten, maar liever een omschrijving in één zin. Ik ben er nog niet helemaal over uit, maar de mailtjes geven mij in ieder geval een seintje als er iets geplaatst is.

**Comment by hans2103** [comment]
Dan kan dit issue gesloten worden toch?

**Comment by hvdmeer** [comment]
Laten we dat doen.
