### ISSUE TITLE
Standaardafbeelding bij artikelen

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#314]
Af en toe worden er JUG verslagen geplaatst waarbij geen afbeelding bij beschikbaar is.
Ik zou willen voorstellen om een standaard afbeelding van JoomlaCommunity bij de intro en volledig artikel als fallback in te stellen.

Dit zodat het visuele plaatje klopt wanneer een bezoeker op de Frontpage / Nieuwspagina komt en het verslag leest.

**Comment by sanderpotjer** [comment]
Of afbeelding verpicht maken :)

**Comment by hvdmeer** [comment]
Is ook goed! Linksom of rechtsom. ;)
![artikel](https://user-images.githubusercontent.com/7062995/51038132-99c99e00-15b2-11e9-9590-f71ccc55502e.png)
![nieuws](https://user-images.githubusercontent.com/7062995/51038133-99c99e00-15b2-11e9-9b6d-09a895bd8fef.png)

**Comment by hans2103** [comment]
- standaard vierkante afbeelding: https://www.joomlacommunity.nl/components/com_rseventspro/assets/images/default/jclogo.png
- standaard rechthoekige afbeelding: (de afbeelding in de footer)
https://www.joomlacommunity.nl/templates/jc/images/jc-pattern.png

**Comment by hans2103** [comment]
<img width="690" alt="Schermafdruk 2019-05-18 16 27 29" src="https://user-images.githubusercontent.com/639822/57971102-df93da00-7989-11e9-9031-6db305cd98af.png">
<img width="1170" alt="Schermafdruk 2019-05-18 16 27 36" src="https://user-images.githubusercontent.com/639822/57971103-df93da00-7989-11e9-985c-3ea20688d005.png">
