### ISSUE TITLE
Update to Joomla 3.9.4 en extensies

### ISSUE THREAD

**Issue by hans2103** [stichtingjoomlanederland/joomlacommunity.nl#319]
https://github.com/joomla/joomla-cms/releases/tag/3.9.4

**Comment by hans2103** [comment]
- [x] Joomla 3.9.2 => 3.94
- [ ] Admin Tools Professional package 5.2.1 => 5.3.0
- [ ] Akeeba Backup Professional package 6.3.3 => 6.4.1
- [ ] EasyDiscuss 4.1.5 => 4.1.6
- [ ] JCE Editor Pro 2.6.35 => 2.6.37
- [ ] PWT ACL 3.2.2 3.2.1 => 3.2.2
- [ ] RSForm! Pro 2.0.15 => 2.1.2

**Comment by hans2103** [comment]
Extensies bijgewerkt en live site kijkt naar branch = master

**Comment by sanderpotjer** [comment]
@hans2103 dank!
