### ISSUE TITLE
Fout 404 bij preview delen op Facebook en LinkedIn

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#321]
Ik wilde vanochtend de laatste blog delen. Het delen op Twitter ging goed maar op Facebook en LinkedIn komen er 404-foutmeldingen bij de preview. Bij de Facebook debug kom ik zo snel niet verder. :(

Het gaat om de volgende URL:
https://www.joomlacommunity.nl/blogs/1469-de-kracht-van-overrides

**Comment by sanderpotjer** [comment]
@hvdmeer niet alleen bij delen, zo te zien staat artikel klaar voor publicatie op de 15e.

**Comment by hvdmeer** [comment]
Well, this is a bit awkward... Bedankt Sander dat jij wel wakker bent.
