### ISSUE TITLE
Veiligheidsupdate EasyDiscuss

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#325]
Ik zag net de melding dat er een veiligheidsupdate is

> Our team has released EasyDiscuss 4.1.10 to address potential SQL injection vulnerability found in prior releases. If your site is running prior to EasyDiscuss 4.1.10, kindly update to the latest version as soon as possible.

**Comment by hans2103** [comment]
Onze licentie is verlopen. Ik heb een mail verzonden naar de mensen van EasyDiscuss met verzoek onze licentie te verlengen.

**Comment by hvdmeer** [comment]
Ik zie dat het forum inmiddels op versie 4.1.11 draait. :)
