### ISSUE TITLE
PerfectImage vervangen door PWT Image

### ISSUE THREAD

**Issue by hans2103** [stichtingjoomlanederland/joomlacommunity.nl#326]
de huidige manier van uploaden van Artikelen via Joomla Article Edit kan verbeterd worden door inzet van PWT Image in plaats van de verouderde Perfect Image. Graag vervangen instellen dat de op de frontend toegepaste ratio ook in backend zichtbaar is.

**Comment by hans2103** [comment]
@Hans2103 bump

**Comment by hans2103** [comment]
@hvdmeer PWT Image is geïnstalleerd en geconfigureerd. PerfectImage is uitgeschakeld, nog niet verwijderd. Behoeft het voor jou nog uitleg? Zo nee, dan issue sluiten aub

**Comment by hvdmeer** [comment]
Uitleg? Ja graag want ik kan er niet mee werken @hans2103 , zie afbeelding. ;-)
![pwtimage-1](https://user-images.githubusercontent.com/7062995/69718647-3172a500-110f-11ea-9dfd-ea48be04294c.png)

**Comment by hans2103** [comment]
@hvdmeer graag nogmaals proberen. Ik heb de ACL instellingen van teams aangepast, waardoor je nu wel toegang zou moeten hebben. 
(mocht het niet lukken, dan ook het issue ana mij toewijzen. Dan weet ik dat de bal bij mij ligt)

**Comment by hvdmeer** [comment]
Bij mij werkt het nu @hans2103 maar krijgt nu iedereen die artikelen kan aanmaken op de website ook deze te zien ipv de oude?

**Comment by hans2103** [comment]
@hvdmeer iedereen die in een subgroep van Team zit krijgt dit te zien

graag issue aan mij toewijzen, indien ik nog iets moet doen. Ook indien een antwoord van me gewenst is, dan graag issue aan mij toewijzen.

**Comment by hvdmeer** [comment]
Het lijkt mij dat iedereen die backend access heeft ook hier toegang tot krijgt. Aangezien ik niet kan zien wie dit allemaal zijn (geen rechten), zou je dit willen controleren en instellen?

**Comment by hans2103** [comment]
geregeld
