### ISSUE TITLE
[com_finder] aanpassen filterwoorden in dropdown

### ISSUE THREAD

**Issue by hans2103** [stichtingjoomlanederland/joomlacommunity.nl#327]
Zijn de filterwoorden overigens aan te passen? Easydiscuss bijvoorbeeld is beter als dat Forum wordt.

_Originally posted by @hvdmeer in https://github.com/stichtingjoomlanederland/joomlacommunity.nl/issues/270#issuecomment-532624345_

https://www.joomlacommunity.nl/zoeken

**Comment by hvdmeer** [comment]
Ik zie nog staan:
Documents
Events

Dat mag dan worden:
Documenten
Agenda

**Comment by hans2103** [comment]
Dat snap ik, maar het is me nog niet gelukt om dat te programmeren.
EasyDiscuss heb ik in de DB handmatig gewijzigd naar forum. Met het legen
van de index wordt deze weer EasyDiscuss
-- 
met vriendelijke groeten,

Hans Kuijpers

HKweb
info@hkweb.nl
http://www.hkweb.nl
tel: +31 654 224 518
twitter: @hans2103

**Comment by hans2103** [comment]
ik heb bij de makers van zowel EasyDiscuss als Events een feature request ingediend met het verzoek de search type multilinguaal te maken.

**Comment by hans2103** [comment]
wijziging in taalstring doorgevoerd en zie dat het werkt.
top!

<img width="595" alt="Schermafdruk 2020-02-05 13 19 25" src="https://user-images.githubusercontent.com/639822/73841111-24aeb380-481a-11ea-812d-d1f309df771b.png">
