### ISSUE TITLE
Rapporteer functie RSComments lijkt niet te werken.

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#330]
Rapporteer functie lijkt niet te werken.
Zie laatste (spam)bericht op: https://www.joomlacommunity.nl/blogs/1493-de-grote-schoonmaak

_Originally posted by @Joomill in https://github.com/stichtingjoomlanederland/joomlacommunity.nl/issues/268#issuecomment-552551308_

**Comment by hvdmeer** [comment]
Ik heb een nieuw issue aangemaakt aangezien het oorspronkelijk issue over EasyDiscuss ging.
In dit geval is het een comment onder een artikel en daarvoor wordt RSComment gebruikt. 

Van een rapporteerfunctie ontvang ik zelf geen bericht. Misschien dat het te maken heeft dat ik daar geen rechten voor heb in de backend. Maar ik mag wel comments verwijderen dus dat heb ik bij deze ook direct gedaan. Bedankt voor het doorgeven Jeroen.

Kan iemand kijken welke instellingen in RSComment staan bij de rapportfunctie?

**Comment by MartijnMaandag** [comment]
Ik heb even gekeken bij de instellingen.
Ik zag dat bij de instellingen opgegeven kan worden naar wie een bericht verstuurd kan worden als gerapporteerd wordt. Dit stond uit. Ik heb nu voorlopig mijzelf opgenomen in deze lijst, zodat ik een bericht krijg.
Wat blijft is dat de rapporteer-functie inderdaad niet werkt. Je krijgt een grijsachtig scherm na rapporteren. Geen idee waarom (ligt denk ik niet aan de rest van de instellingen).

**Comment by hans2103** [comment]
@MartijnMaandag is dit issue nu verholpen? Zo ja, dan sluiten aub.
