### ISSUE TITLE
Nieuwe router gaan gebruiken

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingjoomlanederland/joomlacommunity.nl#331]
Wellicht leuk om de nieuwe router te gaan activeren zodat IDs uit URLs verdwijnen. Uiteraard wel zorgen dat oude links netjes blijven werken.

**Comment by hans2103** [comment]
```
$ curl -s https://www.joomlacommunity.nl/sitemap-xml| grep "<loc>" | awk -F"<loc>" '{print $2} ' | awk -F"</loc>" '{print $1}' |pbcopy
```
Met bovenstaand commando wordt de xml sitemap binnengehaald.
Daarna wordt de url tussen `<loc>` en `</loc>` gehaald.
Daarna wordt het geheel naar klembord gestuurd.

Het geheel plak ik in een Spreadsheet waar ik middels een paar kolommen van oude naar nieuwe url ga

`A2` = `https://www.joomlacommunity.nl/`
INPUT in `A3` =>  `https://www.joomlacommunity.nl/bedrijvengids/1525-hkweb`
OLD URL in `B3` => `=right(A3;len(A3) - (len(A$2) - 1))`
NEW URL `C3` => `=REGEXREPLACE(B3;"(.*)\/[0-9]+-(.*?)$";"$1/$2")`

`D1` = <code>INSERT INTO &#96;his_redirect_links&#96; (&#96;old_url&#96;, &#96;new_url&#96;, &#96;referer&#96;, &#96;comment&#96;, &#96;hits&#96;, &#96;published&#96;, &#96;created_date&#96;, &#96;modified_date&#96;, &#96;header&#96;)</code>
`D2` = `VALUES`
`D3` = `="('"&B3&"','"&C3&"', '', '', 1, 1, '"&C$2&"', '', 301),"`

B3, C3 en D3


[JoomlaCommunity URL redirects.xlsx](https://github.com/stichtingjoomlanederland/joomlacommunity.nl/files/3907263/JoomlaCommunity.URL.redirects.xlsx)


Nog even XLS opschonen van urls die geen ID bevatten 
Daarna de SQL import uitvoeren in de db. 
com_redirect is nu gevuld met redirects van url met id naar url zonder id.

Via de algemene opties van com_content bij tabblad integratie de keus maken voor de vernieuwde url zonder id in de url.

**Comment by hans2103** [comment]
@hvdmeer en @sanderpotjer vanaf nu lopen de Joomlacommunity URL's zonder id.

**Comment by sanderpotjer** [comment]
@hans2103 top! Werkt prima van wat ik heb getest, thnx!

**Comment by hvdmeer** [comment]
Zojuist ook even wat oudere artikelen getest en alles werkte zoals het hoort. Top!
