### ISSUE TITLE
File time in JS / CSS bestanden voor cache busting

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingjoomlanederland/joomlacommunity.nl#332]
Aan CSS / JS de filetime toevoegen van de bestanden, zodat na aanpassing bij iedereen de nieuwere CSS wordt geladen.

**Comment by hans2103** [comment]
@sanderpotjer reeds uitgevoerd middels  commit https://github.com/stichtingjoomlanederland/joomlacommunity.nl/commit/f3e8c9f76e8c78d0e1ed5bf18ff52d036d447047

**Comment by sanderpotjer** [comment]
@hans2103 dan werkt dat niet ben ik bang, in broncode staat namelijk `<link href="/templates/jc/css/template.css" rel="stylesheet" type="text/css" />`

**Comment by hans2103** [comment]
@sanderpotjer Zal inderdaad pas werken als de option `version` meegegeven wordt bij het inladen. :-)
Dat gebeurt nu nog niet. Pas ik aan.

https://github.com/stichtingjoomlanederland/joomlacommunity.nl/blob/0788063eb7f00c7a6aeab8ce45048cab39301bee/public_html/templates/jc/helpers/helper.php#L300-L311

**Comment by sanderpotjer** [comment]
Top, dank @hans2103 !

**Comment by hans2103** [comment]
template css en js worden vanaf nu ingeladen met versie.
Versie is timestamp van de file m time van Joomla root dir. 
```
<link href="/templates/jc/css/template.css?1560457002" rel="stylesheet" type="text/css" />
```
