### ISSUE TITLE
[RSEvents] Een organisator te veel bij de gebruikersgroep

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#333]
Na het toevoegen van de nieuwe bijeenkomst zag ik op de website dat er een nieuwe organisator bij is gekomen bij onze gebruikersgroep. Maar ik denk dat dit een foutje is.
![arnhemnijmegen](https://user-images.githubusercontent.com/7062995/70024809-77aa8700-159b-11ea-94bf-6804e5d7958f.png)
Voor de duidelijkheid, het gaat om hans.kuijpers.

**Comment by hans2103** [comment]
@hvdmeer die was tijdelijk aangemaakt om zichtbaarheid van PWT Image uit issue #326 te testen voor de diverse beheerders. Voor users die geen super user zijn. Het werkt, dus gebruiker verwijderd.

**Comment by hvdmeer** [comment]
Check
