### ISSUE TITLE
Rechten bewerken bedrijvengids

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#335]
Het viel me op dat wanneer ik de bedrijvengids ik daar rechten heb om de toegevoegde bedrijven te kunnen bewerken.

Aangezien het een nieuwe uitbreiding is kan het zijn dat er nog wat juist ingesteld moet worden of gecommuniceerd worden in wie wat mag doen. Maar ik wilde het alvast even melden.

![bedrijvengids-bewerken](https://user-images.githubusercontent.com/7062995/70046117-a4739400-15c5-11ea-9ef1-5ad8743fc941.png)

**Comment by sanderpotjer** [comment]
@hvdmeer jij zit in de gebruikersgroep "Nieuws" en die kunnen bij alle artikelen zo te zien. Bedrijvengids = Joomla artikelen, dus dat klopt dan.

**Comment by hvdmeer** [comment]
Okay, te verwachten dus in functionaliteit. 
Voor mij hoeft hier geen actie op genomen te worden, sluiten dus
