### ISSUE TITLE
Geen code tabblad voor frontend bewerken.

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingjoomlanederland/joomlacommunity.nl#336]
We kregen de opmerking van Rene Kreijveld dat men geen <p> </p> kan invoeren bij het frontend bewerken van de teksten. Heb dat even in de backend gedaan, maar zou denk ik ook op de frontend moeten kunnen?

**Comment by sanderpotjer** [comment]
De html filter stond voor de geregistreerde groepen te streng waardoor deze eruit werd gehaald. Zou nu wel goed moeten gaan.

**Comment by MartijnMaandag** [comment]
Werkt, dank.
