### ISSUE TITLE
Rechten op plugins AcyMailing ivm configuratie

### ISSUE THREAD

**Issue by webmiep** [stichtingjoomlanederland/joomlacommunity.nl#337]
@hans2103,
Kan je voor mij de volgende punten doornemen en aanpassen voor de Nieuwsbrief van JoomlaCommunity?:
- [x] Graag heb ik toegang tot de plugins om een en ander aan instellingen te kunnen doen zonder jou steeds te moeten vragen om te veranderen. Kan jij mij hiertoe de rechten verlenen?
- [x] Verder zou ik graag de socialmedia -cons die in de website gebruikt worden ook in de nieuwsbrief zetten met dezelfde links erachter. Misschien wil je de icons in de media/com_acym/upload/ zetten waar de social icons worden opgeslagen… ik heb daar nu hele slordige staan met witte randjes … Die graag verwijderen.
- [x] Graag gebruik ik Captcha voor het aanmeld formulier? Heb je daar de Google site sleutel en key voor in de configuratie?
- [x] Nu zijn de gebruikers in Joomla nog niet gekoppeld aan de Nieuwsbrief. Mag ik ze aan de Lijst 1 koppelen? Of hebben jullie daarover nog geen besluit genomen? Er is een verschil in de website tussen actieve gebruikers en inactieve ….. maar waarschijnlijk weet je dat.
- [x] Voor wat betreft het Inschrijfformulier welke heb jij staan in de website? AcyMailing subscribtionForm of AcyMailing Module? Graag hoor ik welke zodat ik je kan zeggen wat ik ingevuld wil zien in de verschillende velden.
- [x] Voor de Button op de voorkant denk ik aan een rode button (de kleur van de menubalk van “nieuws” in de website) Dan met witte letters erop “Post ontvangen? Meld je aan!”  of “De JoomlaCommunity Post ontvangen? Meld je aan!” …. Ik heb dit laatste punt nog even aan Rachel voorgelegd.

Groetjes Marianne

**Comment by hans2103** [comment]
> - Graag heb ik toegang tot de plugins om een en ander aan instellingen te kunnen doen zonder jou steeds te moeten vragen om te veranderen. Kan jij mij hiertoe de rechten verlenen?

Ik heb je toegevoegd aan de gebruikersgroep met rechten om Acymailing te beheren

> - Verder zou ik graag de socialmedia -cons die in de website gebruikt worden ook in de nieuwsbrief zetten met dezelfde links erachter. Misschien wil je de icons in de media/com_acym/upload/ zetten waar de social icons worden opgeslagen… ik heb daar nu hele slordige staan met witte randjes … Die graag verwijderen.

png iconen geplaatst in de opgegeven directory
![twitter-square](https://user-images.githubusercontent.com/639822/71005575-2397ba80-20e4-11ea-843f-e525644b5445.png)
![flickr](https://user-images.githubusercontent.com/639822/71005571-22ff2400-20e4-11ea-998d-4319f9d89911.png)
![facebook-square](https://user-images.githubusercontent.com/639822/71005572-22ff2400-20e4-11ea-984b-59754d36b4ee.png)
![linkedin](https://user-images.githubusercontent.com/639822/71005574-22ff2400-20e4-11ea-8617-c0cb3844ea45.png)


> - Graag gebruik ik Captcha voor het aanmeld formulier? Heb je daar de Google site sleutel en key voor in de configuratie?

Via de settings van AcyMailing heb ik zojuist invisible Google reCaptcha v2 ingesteld. 

> - Nu zijn de gebruikers in Joomla nog niet gekoppeld aan de Nieuwsbrief. Mag ik ze aan de Lijst 1 koppelen? Of hebben jullie daarover nog geen besluit genomen? Er is een verschil in de website tussen actieve gebruikers en inactieve ….. maar waarschijnlijk weet je dat.

Ik heb zojuist twee lijsten aangemaakt JUG073 en JUG040. In beide heb ik de subscribers van de Mailchimp lijst JUG073 toegevoegd. Daarna heb ik ze vanuit JUG040 een mail verzonden met de melding dat JUG073 verhuisd is naar JUG040. Plus de melding dat als ze liever geen bericht meer ontvangen je onderaan de mail eenvoudig kunt afmelden. 
Zoiets zou jij voor de website natuurlijk ook kunnen doen. 

Verder bestaat er geen definitie van actieve of inactieve gebruikers. 

> - Voor wat betreft het Inschrijfformulier welke heb jij staan in de website? AcyMailing subscribtionForm of AcyMailing Module? Graag hoor ik welke zodat ik je kan zeggen wat ik ingevuld wil zien in de verschillende velden.

Ik heb de module Acymailing subscription form toegepast bij https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/eindhoven

> - Voor de Button op de voorkant denk ik aan een rode button (de kleur van de menubalk van “nieuws” in de website) Dan met witte letters erop “Post ontvangen? Meld je aan!” of “De JoomlaCommunity Post ontvangen? Meld je aan!” …. Ik heb dit laatste punt nog even aan Rachel voorgelegd.

@webmiep ik hoor graag welke het gaat worden. 

Daarnaast heb ik wat DNS wijzigingen doorgevoerd. TXT records aangemaakt voor SPF en DKIM

**Comment by hans2103** [comment]
@webmiep klein signaal om dit issue bij je onder de aandacht te brengen.
