### ISSUE TITLE
Images portfolio niet getoond, in plaats daarvan melding "Image not autorized. Please sign up for a paid account"

### ISSUE THREAD

**Issue by crommie** [stichtingjoomlanederland/joomlacommunity.nl#338]
Dit is bijvoorbeeld de portfolio van HKWeb:

![afbeelding](https://user-images.githubusercontent.com/11227077/70520532-fecca180-1b3d-11ea-8fea-26492d72e8f2.png)

**Comment by sanderpotjer** [comment]
Ow leuk...dan moeten we een alternatief gaan vinden, blijkbaar zitten we over limiet heen.

**Comment by crommie** [comment]
Of betalen. Dat zeggen ze :)
