### ISSUE TITLE
Badges niet bijgewerkt

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingjoomlanederland/joomlacommunity.nl#339]
Bij user Anja de Crom wordt de badge niet bijgewerkt. Zij heeft inmiddels 106 reacties geplaatst, maar wordt niet zichtbaar bij "de Stem", hoewel iedereen met meer dan 100 reacties zou moeten worden opgenomen.
Ik heb zelf zitten zoeken en vond dit issue bij EasyDiscuss: https://stackideas.com/forums/no-points-earned-or-deducted 
Ik heb vervolgens bij de instellingen van EasyDiscuss - Instellingen - Integraties - EasySocial Gebruik EasySocial puntensysteem uitgeschakeld.
Hierna is er wel een Badge uitgereikt aan Rondeb als Tevreden Joomler op 9 december, maar de Badge van Anja wordt niet toegekend.
Ik weet het eigenlijk niet echt meer. We zouden nog alle "Integraties" uit kunnen zetten, aangezien we die volgens mij toch niet gebruiken?
Daarnaast een badge "Boekenwurm" zou toch ook weleens uitgereikt moeten zijn?
Dit alles is niet echt belangrijk, maar toch....

**Comment by crommie** [comment]
Badge "De Cock" doet het wel. Die is gisteren nog toegekend aan iemand. Toch raar.

**Comment by hans2103** [comment]
ook nog eens naar gekeken, maar krijg het nog niet opgelost.
ook andersom niet,.... als ik lokaal het aantal geplaatste reacties van een gebruiker verlaag, dan zie ik een badge niet automatisch verdwijnen.
Bij de makers zie ik ook niet zo snel hoe een badge automatisch toegekend wordt.

**Comment by hvdmeer** [comment]
It's magical! 🦄
Issue inschieten bij Stackideas?

**Comment by hans2103** [comment]
Een van de andere badges is ijdeltuit. Bij 5 maal wijzigen van je avatar krijg je die badge.
Zojuist succesvol getest door mijn avatar meer dan 5 keer te wijzigen. 
Ik heb de badge ijdeltuit.
Conclusie: het systeem functioneert nog. 

Nu door naar het issue waarom Anja geen badge krijgt.

**Comment by crommie** [comment]
Het systeem werkt in elk geval voor ijdeltuiten. Maar misschien niet voor de Stem, want ander type criterium?

**Comment by hans2103** [comment]
@crommie andere manier van controleren denk ik. Ik ben in de code aan het duiken om te zien wanneer er wat gebeurt.

**Comment by crommie** [comment]
Ik wacht in spanning af.

**Comment by crommie** [comment]
... en we zijn twee maanden verder @hans2103 dat is wel heel erg in-depth in de code duiken :)

**Comment by hans2103** [comment]
@crommie nog geen tijd voor genomen. Bezig met ander vrijwilligerswerk nu

**Comment by hans2103** [comment]
@crommie ben weer een stapje verder

De databasetabel `#___discuss_users_history` geeft slechts 63 reacties op comments gemaakt door jou
De reacties van voor '2018-06-11 18:21:12' staan niet in de tabel. Deze 49 items zijn foetsie. 
Daardoor zit je dus nog onder de drempelwaarde van 100 reacties. 

Juni 2018 is het moment dat de website van JoomlaCommunity.nl overgezet is van Byte hosting naar Combell hosting en die ging niet helemaal vlekkeloos zo blijkt. 

Samen met Easydiscuss ben ik op zoek naar een oplossing.

**Comment by crommie** [comment]
Owwwww Combell! Fijn dat je een oplossing zoekt. Ik kan natuurlijk ook nog een heleboel reacties gaan plaatsen maar ik heb het nogal druk op het moment :)

**Comment by hans2103** [comment]
@crommie 

> If both also don't have, then we can help you manually assign that badge for this user crommie because there is no other easy way around to make the user history table data tally with her reply. 

We gaan handmatig een badge aan jou toekennen, omdat het bijwerken van de tabel `#__discuss_users_history` volgens zeggen not easy is. (dus als je het mij vraagt wel mogelijk, maar kost waarschijnlijk te veel tijd)

**Comment by hans2103** [comment]
<img width="283" alt="Schermafdruk 2020-06-30 09 46 11" src="https://user-images.githubusercontent.com/639822/86098566-97187c80-bab6-11ea-9515-c841342c5749.png">


Badge handmatig toegekend 
```
INSERT INTO `huqnd_discuss_badges_users` (`id`,	`badge_id`, `user_id`,`created`, `published`, `custom`) VALUES (70, 7, 2863, '2020-06-30 15:29:07', 1, '');
```

@crommie bij de volgende mijlpaal weer even roepen. :-)
