### ISSUE TITLE
[Forum] Sluiten topic alleen openingsbericht zichtbaar

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#341]
Wanneer er een Onderwerp gesloten wordt is daarna voor gewone gebruikers alleen nog maar het eerste initiele bericht zichtbaar. Alle andere berichten in het Onderwerp zijn niet meer zichtbaar.

Zelf kan ik ze nog wel zien met mijn rechten. Op het ED-forum zag ik hier geen melding van, wellicht dat dit een lokaal probleem is.

Edit: op dit moment sluit ik alleen nog maar Service aanvragen die afgehandeld zijn.

Edit 2: kan er gekeken worden of het mogelijk is dat weer alle berichten zichtbaar  zijn als een onderwerp gesloten is? Zoals het"vroeger" wel was?

**Comment by hvdmeer** [comment]
Net gecontroleerd, nog steeds niks hierover op het Stackideas forum. Zou iemand kunnen kijken of dit probleem bij ons ligt of bij EasyDiscuss?

**Comment by hvdmeer** [comment]
Net weer gecontroleerd, nog steeds niks hierover op het Stackideas forum. Zou iemand kunnen kijken of dit probleem bij ons ligt of bij EasyDiscuss?

**Comment by hans2103** [comment]
Screenshot van hetgeen ik zie als ik niet ingelogd ben

<img width="1315" alt="Schermafbeelding 2020-09-07 om 08 53 24" src="https://user-images.githubusercontent.com/639822/92357138-a8e65380-f0e7-11ea-9ddb-e5b0b49324aa.png">

**Comment by hvdmeer** [comment]
![Naamloos](https://user-images.githubusercontent.com/7062995/92357568-5a858480-f0e8-11ea-923a-1ce6530f57dc.png)

**Comment by hans2103** [comment]
New topic started on Stackideas: https://stackideas.com/forums/display-entire-discussion-closed-topic

**Comment by hvdmeer** [comment]
In een privévenster zijner in te loggen gecontroleerd en inderdaad is nu de hele discussie te zien.
Bedankt @hans2103 !
