### ISSUE TITLE
[Frontpage] Gepland artikel is niet als dusdanig te herkennen

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#344]
Wanneer een artikel ingepland staat is deze met mijn rechten al zichtbaar op de frontend van de website. Dit op de homepage en vanuit de nieuws & blog menu links.

Alleen is er (voor mij) niet zichtbaar dat het een ingepland artikel is. Omdat ik wel via de sociale kanalen de berichten deel is het wel handig dat ik kan zien dat het om een gepland artikel gaat en niet pas bij een foutmelding van de scraper van het betreffende sociale kanaal er achter kom.

Kan dit gefixt worden zodat er wel aangegeven wordt ?
Joomlacommunity
![blog-gepland](https://user-images.githubusercontent.com/7062995/74406210-51bd2080-4e2f-11ea-9a60-8402e09e3037.jpg)

Persoonlijke website
![blog-gepland-zelf](https://user-images.githubusercontent.com/7062995/74406304-96e15280-4e2f-11ea-9445-62a5f937e765.jpg)

**Comment by hans2103** [comment]
@hvdmeer label toegevoegd en wordt, indien nodig, getoond bij artikel of in category overview


<img width="244" alt="Schermafdruk 2020-03-12 21 17 32" src="https://user-images.githubusercontent.com/639822/76563206-41887780-64a7-11ea-82e8-1476716a1550.png">

**Comment by hvdmeer** [comment]
Merge into develop, dus niet niet online @hans2103 ?

**Comment by hans2103** [comment]
Verwerkt op live. Zie commits

https://github.com/stichtingjoomlanederland/joomlacommunity.nl/commits/master


-- 
met vriendelijke groeten,

Hans Kuijpers

HKweb
info@hkweb.nl
https://hkweb.nl
tel: +31 654 224 518

**Comment by hvdmeer** [comment]
Getest en het werkt.
