### ISSUE TITLE
reactie op artikel

### ISSUE THREAD

**Issue by slibbe** [stichtingjoomlanederland/joomlacommunity.nl#345]
Als ik reageer op een artikel, krijg ik wel een bedankje voor de reactie te zien, maar ik moet refreshen om de reactie zelf ook te zien.

Lijkt me dat dat anders moet kunnen.

**Comment by hans2103** [comment]
@slibbe heb je een url voor me? Dan ga ik na of ik dat kan reproduceren.

**Comment by hans2103** [comment]
Ik heb gereageerd op topic https://github.com/stichtingjoomlanederland/joomlacommunity.nl/issues/345
en zie direct mijn antwoord verschijnen. 

Ik denk dat dit issue reeds opgelost is.
![Schermafbeelding 2022-06-21 om 13 25 43](https://user-images.githubusercontent.com/639822/174788486-b38081ae-678b-4e13-b5a9-7f6ff37d3821.png)
