### ISSUE TITLE
Invisible captcha bij aanmelden voor bijeenkomst.

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingjoomlanederland/joomlacommunity.nl#349]
Je krijgt "Please resolve the Captcha challenge." als je je wil aanmelden voor een evenement.
https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/maastricht/event/508-jug043-bijeenkomst-demo-rsform-pro-basis 
Aanmelden en vervolgens opslaan.
Invisble captcha geïmplementeerd?

**Comment by hvdmeer** [comment]
Ook niet een Block/ghostery aan staan?

**Comment by hans2103** [comment]
@MartijnMaandag @hvdmeer ik heb bij de settings van RSEvents Pro zojuist gekozen voor hCaptcha en de settings gevuld. 
Via een comment op het bovengenoemde event heb ik Fred verzocht nogmaals te testen

**Comment by MartijnMaandag** [comment]
Ik heb het geprobeerd en krijg nog steeds "Please resolve the Captcha challenge."
Heb mijn VPN uitgezet en dan nog...
Zie dat Johan wel aangemeld is, Ik weet niet wat hij anders gebruikt (ik heb het geprobeerd op Windows - Firefox en op Android telefoon met Chrome).
Lukt het jou wel Hans?

**Comment by hans2103** [comment]
@MartijnMaandag omdat je ingelogd moet zijn om je aan te melden voor een event zie ik eigenlijk geen noodzaak een reCaptcha veld toe te voegen aan het aanmeldformulier. Ik heb hem daarom uitgeschakeld voor het aanmelden.

**Comment by MartijnMaandag** [comment]
Is prima, werkt voor mij ook, dank!

**Comment by MartijnMaandag** [comment]
We kregen net een bericht binnen van Arjan Booy dat het reageren op een activiteit niet lukt ("Ongeldige captcha").
Ik heb het net even uitgeprobeerd en zie dat, als je niet ingelogd bent, dit bericht verschijnt zonder de mogelijkheid om een captcha in te vullen.
Bij het registreren vind ik overigens wel een reCAPTCHA.

**Comment by Joomill** [comment]
Ook hier hetzelfde probleem.

![afbeelding](https://user-images.githubusercontent.com/1471185/94539521-9de59580-0245-11eb-8501-ae2e412d5960.png)

**Comment by hans2103** [comment]
issue reeds opgelost
