### ISSUE TITLE
RSJoomla vertalingen update systeem XMLs

### ISSUE THREAD

**Issue by conconnl** [stichtingjoomlanederland/joomlacommunity.nl#350]
Zouden we de update XMLs voor de vertalingen van Extensies, in dit geval die van RSJoomla in de folder "https://github.com/stichtingjoomlanederland/joomlacommunity.nl/tree/develop/public_html/updates" kunnen plaatsen op de JC Website?

Het centraliseren hiervan biedt toekomstige mogelijkheden voor andere om updates beschikbaar te stellen, maar ook om andere Nederlandse vertalingen eventueel te automatiseren.

**Comment by webmasterab** [comment]
Dit is een goed idee.
Ik hou deze in de gaten en hoop dat we met velen kunnen helpen om componenten, plugings te kunnen vertalen in het Nederlands.

**Comment by hans2103** [comment]
@conconnl Ik denk dat het een goed idee is om de update.xml voor vertalingen van extensies op de website te plaatsen. 
Ik kan me namelijk niet voorstellen dat de door jouw bijgehouden RSForm vertaling, zoals die aangeboden wordt op https://www.joomlacommunity.nl/downloads/extensie-vertalingen/25-rsjoomla-vertalingen, up to date is. 
@webmasterab had dit goed geconstateerd. Zo te zien heeft hij toch nog contact met je opgenomen. 

Het liefst zou ik een manier van verwerken zien waarbij de beheerders van joomlacommunity.nl weinig tot geen onderhoud hebben aan het up to date houden van de aangeboden versies van de vertalingen. 

> Ik hou deze in de gaten en hoop dat we met velen kunnen helpen om componenten, plugings te kunnen vertalen in het Nederlands.

@conconnl je hebt er  zo te zien een vertaler bij. :-)

**Comment by conconnl** [comment]
De pagina zelf heb ik nooit geüpdatet omdat de download knop simpelweg naar mijn website verwijst.
Sommige zijn meer up-to-date dan andere, ligt er maar net aan hoeveel tijd er is en hoeveel mensen dingen aanleveren.
Dit heb ik gisteren kunnen oplossen, heb kunnen regelen dat we een gratis account op Crowdin hebben, wat dus betekend dat iedereen kan helpen met vertalen.

**Centraliseren is altijd beter**
We hebben meerdere stappen te organiseren, natuurlijk op zo'n manier dat we het minste werk eraan hebben.
* De update XMLs in de map op de server, zodat ze niet op verschillende websites staan.
* Crowdin inrichten, zodat vele Nederlanders kunnen helpen.
* Wellicht GitHub repositories om te synchroniseren met Crowdin Project, waarmee je dan de source automatisch upload en de vertalingen download. (Doen we ook met de JOrg delen).
* Dan wat automatiseren, dat bijvoorbeeld op basis van een configuratie bestand de taalbestanden in de correcte structuur in een zip geplaatst worden, wat gelinkt is van de download site en update XML. 

Ik doe nu Crowdin handmatig inrichten, als we onder deze organisatie een Repository aanmaken "Vertalingen - RSJoomla" dan zou ik die zo kunnen inrichten dat hij met Crowdin praat. Dan hebben we gelijk een voorbeeld voor andere zoals J2Store, YourSites, Hikashop, etc.

**Comment by webmasterab** [comment]
@hans2103 Inderdaad heb ik contact opgenomen met @conconnl en zo is dit ontstaan.
En ja ik ga proberen zo veel ik kan, en zo goed als ik kan te vertalen.
Het is belangrijk en kan nu centraal gedaan worden.
En iedereen die wil helpen kan dit nu eenvoudig doen.
Het werkt super in Crowdin.

**Comment by hans2103** [comment]
@conconnl wat moet er nog gebeuren voordat we dit issue kunnen sluiten?

**Comment by conconnl** [comment]
Van mij mag hem sluiten. 
De situatie is verandert, door de hulp van Crowdin hebben we officiële project kunnen maken onder de Joomla vlag, maar beheerd door de extensie ontwikkelaars. 
Zij kunnen dus dan de bron bijhouden en de vertalingen zippen en leveren aan de gebruiker. 

RSJoomla is bezig met de inrichting, vertaal zip methode en dergelijke. Wij gaan natuurlijk geen dubbel werk doen.

**Comment by hans2103** [comment]
Closed by request
