### ISSUE TITLE
[SPAM] Gewijzigd onderwerp op het forum, andere auteur?

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#352]
Ik zag een melding voorbij komen over spam en toen ik even het bericht bekeek snapte ik er niks van. Dit heb ik één keer eerder gezien maar snappen doe ik het niet.

Het onderwerp:
https://www.joomlacommunity.nl/index.php?option=com_easydiscuss&view=post&id=18952

Er is ooit een legitieme vraag gesteld want ik heb een normaal antwoord gegeven. Hoe is het mogelijk dat nu er een vietnamees spam bericht hiervoor in de plek staat? 

Zou het wellicht een copy/paste vraag in het Nederlands als oorspronkelijk bericht geweest zijn?
Kan iemand hier iets over zeggen? Het bericht laat ik even staan zodat anderen hier eventueel een licht op kunnen schijnen.

**Comment by crommie** [comment]
Rare kronkel misschien, maar: user account gehackt?

**Comment by MartijnMaandag** [comment]
Ik heb even naar de user gekeken in de back-end.
Registratiedatum: 14-02-2019
Laatste bezoek: 14-07-2020
Kan iemand na zo'n lange tijd zijn bericht aanpassen?

**Comment by crommie** [comment]
Ja dat kan. Ik heb net een stokoud bericht aangepast.

**Comment by MartijnMaandag** [comment]
Ja, ik mag alles aanpassen ;-)
Kon ik dus niet testen. Ik heb net gezocht of er een instelling bij EasyDiscuss is waarbij je de tijd dat dit kan kunt instellen. Nog niets gevonden.

**Comment by MartijnMaandag** [comment]
Ik heb een vraag gesteld bij Stackideas of bewerken van een bericht na een periode uitgeschakeld kan worden.

**Comment by crommie** [comment]
Intussen zou je natuurlijk ergens kunnen checken vanaf welk IP-adres de laatste inlog is geweest. Dan weet je of het account gehackt is. Misschien sowieso het account anonimiseren of zo?

**Comment by MartijnMaandag** [comment]
Aanpassing van bericht komt uit dezelfde regio (Azië) als de oorspronkelijke aanmelding van het account.
Stackideas geeft aan dat er geen optie is om het bewerken na een bepaalde periode uit te schakelen. Ze suggereren alles onder een moderator te laten plaatsen, maar dat gaat mij te ver.
Ik heb gevraagd of ze eventueel willen regelen dat het bewerken van een bericht nadat het is opgeslagen helemaal onmogelijk kunnen maken via een optie.
Ik vind wijzigen altijd al vervelend. Mensen kunnen dan een hele discussie onleesbaar maken door hun bericht leeg te maken.

**Comment by hvdmeer** [comment]
Ben ik mee eens Martijn. Het zou mooi zijn dat een bericht op slot komt na bijvoorbeeld een dag (om maar wat te zeggen) en dat alleen iemand met meer rechten dat kan wijzigen.

**Comment by MartijnMaandag** [comment]
Reactie van Easydiscuss: Als we de mogelijkheid om het artikel aan te passen via een optie onmogelijk willen maken (of slechts een bepaalde tijd), moeten we maar een voorstel doen via https://stackideas.com/voices/easydiscuss , waarna het, als er genoeg medestanders zijn, misschien wordt geïmplementeerd.
Ze gaven nog wel een oplossing die misschien iets voor ons kan zijn:
By the way, you can disable those edit own reply and question from backend > Easydiscuss > ACL > edit your Joomla user group which you would like to disable that edit functionality.

**Comment by conconnl** [comment]
Heb je dit via de mail besproken, zoja kun je deze dan doorsturen?
Of wellicht in het openbare forum gevraagd?

Dan ga ik even iemand contacteren voor je.

**Comment by MartijnMaandag** [comment]
Ik heb een ticket aangemaakt en het daar besproken: [#512033]: Edit post after a long period.
Via taal@joomlacommunity.eu

**Comment by conconnl** [comment]
Dankje...
Ticket nummer kan ik wel iets mee.

**Comment by conconnl** [comment]
StackIdeas is aan het kijken of ze de optie toe kunnen voegen in 4.1.18 of wellicht in 4.2.
In ieder geval gaat deze er komen, Mark doet zijn best om het snel erin te krijgen.

**Comment by MartijnMaandag** [comment]
Dank @conconnl

**Comment by MartijnMaandag** [comment]
@hvdmeer Ik heb het bericht maar verwijderd uit het forum en de auteur uitgeschakeld.

**Comment by conconnl** [comment]
@hvdmeer @MartijnMaandag 
De EasyDicuss versie is beschikbaar: https://stackideas.com/blog/easydiscuss-4118-released

<img width="948" alt="image" src="https://user-images.githubusercontent.com/11913918/89173574-c7a37880-d584-11ea-9c06-631eb94509b7.png">

**Comment by hvdmeer** [comment]
Nu mag iemand de update via Git uitvoeren.

**Comment by MartijnMaandag** [comment]
Ik kan dat niet.
Waar gaan we daarna de waarde op zetten? Wat mij betreft 2 uur?

**Comment by MartijnMaandag** [comment]
Na implementatie bleek in het beheergedeelte dat de waarde vrijwel niet zichtbaar was. Heb opnieuw een issue ingeschoten bij StackIdeas. Hierop een oplossing gekregen welke @hans2103 heeft geïmplementeerd. Het is nu goed zichtbaar en deze oplossing komt waarschijnlijk in de volgende release.
Je kunt nu dus (in dagen) aangeven hoelang de post te wijzigen is. Ik heb dit op één ingesteld.
Ik denk dus dat het is opgelost.
