### ISSUE TITLE
Mediavelden in bedrijvengids werken niet

### ISSUE THREAD

**Issue by Joomill** [stichtingjoomlanederland/joomlacommunity.nl#353]
In de bedrijvengids is het niet meer mogelijk om foto's toe te voegen of te wijzigen.

![afbeelding](https://user-images.githubusercontent.com/1471185/90943630-e2963980-e41a-11ea-9dc9-3ca7b46c059c.png)

**Comment by hvdmeer** [comment]
Ik kreeg hier ook de vraag over van Maarten en ik mag zelf ook geen afbeeldingen plaatsen.

**Comment by sanderpotjer** [comment]
@Joomill @MartijnMaandag @hvdmeer zou weer moeten werken, heb de rechten aangepast (zijn er bij recente update bijgekomen) @hans2103 FYI

**Comment by Joomill** [comment]
Thnx @sanderpotjer 
hij werkt nu.
