### ISSUE TITLE
[Forum] Bio onder artikelen

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#356]
> Opmerkingen/aanpassingen voorstel vanwege de update van EasyDiscuss naar V5 en het overgaan naar de "standaard" template

- [ ] Onder de artikelen op de voorzijde hing altijd de bio van de auteur, deze mist nu

![JC-bio-auteur-artikel](https://user-images.githubusercontent.com/7062995/109068665-73164500-76f0-11eb-9bc1-218e123086d0.png)
![JC-bio-auteur-artikel-huidig](https://user-images.githubusercontent.com/7062995/109069044-f9328b80-76f0-11eb-9d6f-60e1fa77942d.png)

**Comment by hans2103** [comment]
<img width="1163" alt="Schermafbeelding 2021-03-12 om 09 24 04" src="https://user-images.githubusercontent.com/639822/110912863-b984ba00-8314-11eb-8d32-cff11d55bd37.png">

**Comment by hvdmeer** [comment]
Inderdaad werkt dit weer @hans2103 .
Mag ik nog vragen hoe het zit met de forum codes zoals [b] en [u] in de handtekening? Dat werkte voorheen niet en nog steeds niet. Is dit op te lossen of gaat dat niet?

**Comment by hans2103** [comment]
Als ik in easydiscuss kan terugvinden hoe ik markdown om kan zetten naar html, dan wordt het opgelost

**Comment by hans2103** [comment]
issue opgelost van #285
