### ISSUE TITLE
[Forum] Informatiebalk bericht forum

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#357]
> Opmerkingen/aanpassingen voorstel vanwege de update van EasyDiscuss naar V5 en het overgaan naar de "standaard" template

De opmaak van de infobalk van de berichten (openingsbericht en reacties) zien er wat karig uit qua opmaak. Nu ben ik niet iemand die goed is in opmaak maar wellicht dat deze wat opgepoetst kan worden? Ik denk zelf aan:
 
- [ ] Lettertype vergroten
- [ ] Achtergrondkleur balk iets meer laten zien qua

 kleur
![infobalk-openingsbericht-oud](https://user-images.githubusercontent.com/7062995/109069722-e7051d00-76f1-11eb-9e4d-50fefc73f73a.png)
![infobalk-openingsbericht-huidig](https://user-images.githubusercontent.com/7062995/109069729-e8cee080-76f1-11eb-8d09-1eb3b5c57d1f.png)

**Comment by hans2103** [comment]
Issue lijkt mij inmiddels opgelost
