### ISSUE TITLE
[forum] Handtekening op forum

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#358]
> Opmerkingen/aanpassingen voorstel vanwege de update van EasyDiscuss naar V5 en het overgaan naar de "standaard" template

De opmaak van een handtekening is voor verbetering vatbaar
- [ ] Padding toevoegen
- [ ] Klopt het font?

![handtekening-forum-oud](https://user-images.githubusercontent.com/7062995/109071320-de154b00-76f3-11eb-9909-9843128ae350.png)
![handtekening-forum-huidig](https://user-images.githubusercontent.com/7062995/109071326-dfdf0e80-76f3-11eb-843b-60a52b61d868.png)

**Comment by hans2103** [comment]
Font-size van signature is in nieuw design van Easydiscuss 75% van normaal en dus kleiner. 
Padding toegevoegd en streep onder de signature verwijderd

![Schermafbeelding 2021-03-11 om 19 11 16](https://user-images.githubusercontent.com/639822/110834257-9f5bc500-829d-11eb-8da2-c4db38b2b3f7.png)

**Comment by hvdmeer** [comment]
Ik vind het prima zo!
