### ISSUE TITLE
[Forum] Editor - emoticons niet goed weergegeven

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#359]
> Opmerkingen/aanpassingen voorstel vanwege de update van EasyDiscuss naar V5 en het overgaan naar de "standaard" template

- [ ] De emoticon knoppen van de editor worden niet goed weergegeven
![editor-forum-huidig](https://user-images.githubusercontent.com/7062995/109071808-7c091580-76f4-11eb-9381-d4e8a8b2161c.png)

**Comment by hans2103** [comment]
@hvdmeer opgelost middels uitschakelen van custom css voor subsite forum
![Schermafbeelding 2021-03-02 om 09 16 26](https://user-images.githubusercontent.com/639822/109618606-08259d80-7b38-11eb-8ead-d30fa0010c9d.png)

**Comment by hvdmeer** [comment]
Perfect, kan deze gesloten worden :)
