### ISSUE TITLE
[forum] PM functie

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingjoomlanederland/joomlacommunity.nl#360]
De PM functie (en Inbox-functie) op het forum is na de update uitgeschakeld.

**Comment by hans2103** [comment]
@MartijnMaandag uitgeschakeld en wordt zelfs verwijderd
![Schermafbeelding 2021-03-02 om 09 19 33](https://user-images.githubusercontent.com/639822/109618906-6b173480-7b38-11eb-9218-50600c6c282e.png)

**Comment by MartijnMaandag** [comment]
Prima, maar mag dan ook de Inbox uit het menu?

**Comment by hans2103** [comment]
ja hoor... geen probleem. Ik heb het menu item uitgeschakeld

**Comment by MartijnMaandag** [comment]
Dank

**Comment by Joomron** [comment]
Jammer dat PM-functie is uitgezet! Leden die er zelf niet uitkwamen die kon je dan nog via pm (belangeloos) helpen.

**Comment by hans2103** [comment]
@Joomron
> Jammer dat PM-functie is uitgezet! Leden die er zelf niet uitkwamen die kon je dan nog via pm (belangeloos) helpen.

Inderdaad jammer... wellicht dat je de makers van EasyDiscuss kunt overtuigen om het weer in te bouwen

**Comment by Joomron** [comment]
> 
> 
> @Joomron
> 
> > Jammer dat PM-functie is uitgezet! Leden die er zelf niet uitkwamen die kon je dan nog via pm (belangeloos) helpen.
> 
> Inderdaad jammer... wellicht dat je de makers van EasyDiscuss kunt overtuigen om het weer in te bouwen

@hans2103 bedankt voor je snelle reactie.

Vreemd/raar dat ze zo'n belangrijk functie niet meer ondersteunen voor op een forum is het toch wel belangrijk.

Wanneer een van de leden er echt niet uitkwam dan kon je hem/haar via pm nog helpen.

Groeten Ron

**Comment by MartijnMaandag** [comment]
Ik vind in een discussie van november 2020 op het forum van Easydiscuss het volgende:

> Just an update on this, we are looking at the possibility of adding this functionality back into EasyDiscuss 5 until we are able to find a better transition for existing users who use the conversations feature on EasyDiscuss in the future.

Ik zal die discussie nog een keer aanzwengelen.

**Comment by MartijnMaandag** [comment]
Ik kreeg al heel snel dit antwoord:

> You could actually enable the legacy conversation feature in EasyDiscuss 5. Are you having issues with that? It was initially disabled in the beta but we have since added it back in 5.0.1

Kan dat @hans2103 ?

**Comment by hans2103** [comment]
@MartijnMaandag Joomla Administrator > Componenten > EasyDiscuss > Instellingen > Algemeen > Gesprekken > Activeer Gesprekken = JA

> DEPRECATED
EasyDiscuss conversation will no longer be available and it will be removed in the next release.

**Comment by Joomron** [comment]
> > DEPRECATED
> > EasyDiscuss conversation will no longer be available and it will be removed in the next release.

Wat willen ze daarmee zeggen? Dat het in een volgende release helemaal er niet meer in zit?

**Comment by MartijnMaandag** [comment]
Ja, maar men schijnt toch aan een alternatief te werken als ik het forum bij Easydiscuss goed begrijp.

**Comment by Joomron** [comment]
We wachten geduldig af meer kunnen we niet doen.

Een goed weekend.

Groeten Ron

**Comment by MartijnMaandag** [comment]
Nog even een  reactie van StackIdeas over het verwijderen van de mogelijkheid om onderling te communiceren:

> As of now, it will not be removed. It will only be removed once ConverseKit is released for free and everyone can then migrate to ConverseKit with a built-in migrator.
