### ISSUE TITLE
[Forum] Structured data instellingen

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#361]
Er zijn Structured data instellingen voor EasyDiscuss. Ik ben zelf daar niet bekend mee, wellicht dat iemand hier naar kan kijken of hier iets handig ingesteld kan worden?

**Comment by hans2103** [comment]
@hvdmeer waar kan ik de structured data instellingen vinden? Heb je de route naar deze pagina voor me?

**Comment by hvdmeer** [comment]
Oeps @hans2103 , dat had ik wel willen toevoegen...
Algemeen - Layout en dan aan de rechterkant

**Comment by hans2103** [comment]
@hvdmeer 
Niet veel te zien onder dat kopje. Wellicht volgt er later nog meer 
Ik heb nu het logo toegevoegd. 

![Schermafbeelding 2021-03-11 om 18 58 12](https://user-images.githubusercontent.com/639822/110832615-cb764680-829b-11eb-8f98-07623e3a73f5.png)

**Comment by hvdmeer** [comment]
Okay, dan stopt het hier gewoon :)
