### ISSUE TITLE
[Forum] verschil in achtergrond hoofpagina forum en "Recent"

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#362]
Er zit een verschil in opmaak tussen de homepage van het forum en de Recent-pagina hiervan. Het lijkt me verstandig om deze gelijk te trekken.

![forum-achtergrond-1](https://user-images.githubusercontent.com/7062995/109434440-a2d98b80-7a15-11eb-904c-f3ae5d933f8d.png)

![forum-achtergrond-2](https://user-images.githubusercontent.com/7062995/109434439-a240f500-7a15-11eb-89cd-38156d1f48fa.png)

**Comment by hans2103** [comment]
@hvdmeer Dan ga ik de padding en blauwe achtergrond van homepage verwijderen, zodat we minder _kadertjes_ hebben
