### ISSUE TITLE
[EasyDiscuss] Melding in beheerszijde

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#364]
Ik zie als ik naar EasyDiscuss ga in de beheerszijde de volgende melding staan. Nu wil ik er best wel op klikken maar ik gooi het toch maar even in de groep

> System detected some of your posts has out-of-sync data. Please click on the 'Fix Now' button to synchronize your post's data.

**Comment by hans2103** [comment]
@hvdmeer klik maar op de FixNow button

**Comment by hvdmeer** [comment]
Nou, dat was een afknapper. Na op Fix klikken en daarna op Start stond de teller direct op 100% en leek alles nog te functioneren.
