### ISSUE TITLE
[Forum] Gebruikers zonder zichtbare naam?

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#365]
Bij het controleren van de fix voor de handtekening viel het me ineens op dat ik een gebruiker zonder naam zag. Dit terwijl deze eerst wel zichtbaar was.

Als ik kijk in EasyDiscuss staat wel alles netjes ingevuld. Met Browser Inspector Tools zie ik wel dat de verbinding met EasyDiscuss voortijdig verbroken werd maar of dit nu de reden is kan ik niet zeggen.

Het gaat in ieder geval op dit moment voor twee gebruikers:

- https://www.joomlacommunity.nl/forum/gebruikersgroepen-nederland-en-belgie/hamburger-menu-joomla
- https://www.joomlacommunity.nl/forum/overige-vragen/foutmelding-404

![2021-03-12-gebruiker-zonder-naam](https://user-images.githubusercontent.com/7062995/110904721-b7692e00-8309-11eb-9da1-7624883f85f4.png)

**Comment by MartijnMaandag** [comment]
Ik heb gekeken wat de verschillen zijn met iemand die zich net heeft aangemeld.
Bij een net aangemelde gebruiker (Jammy67) staat de roepnaam ingevuld (gelijk aan alias). Bij Karin (foutmelding 404) staat die niet ingevuld en ron-vos20 (hamburger) staat de roepnaam ook niet ingevuld.
Als ik probeer bij mijzelf in het profiel de roepnaam leeg te maken dan lukt dat niet.
Ik heb nu bij beiden de roepnaam ingevuld met de naam die bij alias staat en daarmee is het probleem opgelost. Ik weet niet hoe het is ontstaan.

**Comment by MartijnMaandag** [comment]
Ik zie nu weer nieuwe gebruikers verschijnen zonder roepnaam, waarbij niets getoond wordt. Voorbeeld Broekie (id= 12967) . Ik weet niet waarom dit opeens zo is en hoe we dit kunnen voorkomen.

**Comment by hvdmeer** [comment]
Ik weet niet of er iets aangepast is maar ik zie in ieder geval sinds gisteren overal namen staan, en jij @MartijnMaandag ?

**Comment by hvdmeer** [comment]
We kunnen ook de instelling aanpassing in EasyDiscuss. Die staat nu op roepnaam maar er is ook de mogelijkheid voor 
- Echte naam
- Gebruikersnaam

**Comment by MartijnMaandag** [comment]
Ik had het idee dat er een periode is geweest dat dit niet goed ging (Roepnaam niet ingevuld). Testen wees uit dat het wel goed gaat.
Ik heb daarom van een aantal mensen die geen roepnaam hadden de roepnaam ingevuld.
Wil nu even kijken of er nog mensen zonder roepnaam verschijnen.

**Comment by hvdmeer** [comment]
Ik heb de oplossing gevonden! Gewoon de update van EasyDiscuss uitvoeren:

> Fixed issue with missing names when their nickname is removed from their profile
> Monday, 15 March 2021 11:46 · Modified Files (1)
> Modified Files:  Administrator/components/com_easydiscuss/tables/profile.php
