### ISSUE TITLE
[Forum] - [code type="markup"] blok aanpassen met een wrapping?

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#367]
Wanneer iemand wat code classificeert als code met [code type="markup"] dan wordt een regel langer dan het bericht niet afgebroken en gaat niet door op een volgende regel. 

Is dit wellicht aan te passen of moet dit bij StackIdeas aangekaart worden?
[Voorbeeld](https://www.joomlacommunity.nl/forum/overige-vragen/warning-creating-default-object-from-empty-value)

**Comment by hans2103** [comment]
@hvdmeer aangepast en verwerkt op de live site. 

![Schermafbeelding 2021-03-23 om 08 35 49](https://user-images.githubusercontent.com/639822/112110158-cd50db80-8bb2-11eb-8193-af1edfe4ea6c.png)

**Comment by hvdmeer** [comment]
Perfect!
