### ISSUE TITLE
Contactpagina werkt niet

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingjoomlanederland/joomlacommunity.nl#368]
De contactpagina geeft altijd aan dat niet alles is ingevuld ("Vul alle verplichte velden in."), terwijl dat zo te zien wel zo is, ofwel het formulier kan niet gebruikt worden.

**Comment by MartijnMaandag** [comment]
Dit is nog steeds het geval.

**Comment by hans2103** [comment]
zo te zien is dit issue al opgelost.

![Schermafbeelding 2022-01-17 om 11 46 17](https://user-images.githubusercontent.com/639822/149755643-2eead77a-a012-46a9-84f4-faa5a0ee5255.png)
