### ISSUE TITLE
Presentatie agenda op de site

### ISSUE THREAD

**Issue by Luchen6** [stichtingjoomlanederland/joomlacommunity.nl#369]
Ik vind de presentatie van de agenda op de site onduidelijk. Het is bij eerste blik niet duidelijk wanneer een evenement wordt gehouden. 

Het zou, naar mijn idee,  verbeteren als het logo van de organiserende JUG op dezelfde hoogte komt te staan als de datum in plaats van de titel. of de datum van de bijeenkomst onder de tekst.

Mogelijk ook een lijntje tussen elk agenda onderwerp.

**Comment by hans2103** [comment]
@Luchen6 heb je het dan over het overzicht van de homepage?
![Schermafbeelding 2022-01-17 om 11 47 20](https://user-images.githubusercontent.com/639822/149755844-1c2feda5-c22b-4f8b-9f9d-7c695a1cfd91.png)

**Comment by Luchen6** [comment]
Ik bedoelde de presentatie als je kiest voor de optie 'Bekijk de Joomla agenda'.

Het is volgens mij overigens al iets gewijzigd. De datum staat nu boven de korte tekst.

![Capture](https://user-images.githubusercontent.com/6205641/149756919-e2db5f27-e650-4315-8acc-fd24ecfc8094.PNG)

**Comment by hans2103** [comment]
Dan sluit ik dit issue
