### ISSUE TITLE
Mailverwerking is uitgezet

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#370]
Het viel me onlangs op dat ik geen mailtjes meer ontvang als er nieuwe vragen geplaatst worden op het forum. Net werd me dat weer duidelijk toen ik zag dat er een x-aantal spam onderwerpen aangemaakt waren. Bij het ontvangen van mails zal me dat eerder opvallen.
> Uw beheerder heeft de e-mail verwerkingsfunctie uitgeschakeld. Zorg ervoor dat uw abonnement interval op Direct staat om door te gaan met ontvangen van e-mail berichten. 

Is er een reden waarom deze e-mailverwerkingsfunctie uit is geschakeld?

**Comment by sanderpotjer** [comment]
@hvdmeer dit zou inmiddels al weer enige tijd wel moeten werken
