### ISSUE TITLE
[RSComment] Comment rapporteren lukt niet

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#372]
Wanneer je een commentaar op de frontpage bij een artikel wil rapporteren lijkt er een popover te komen want de site wordt donkerder maar met geen mogelijk kan je iets zien waar je op moet "klikken".

Er is ook geen sluitknop dus het enige wat je kan doen is terugnavigeren.

**Comment by hans2103** [comment]
Ook op desktop zie ik niet de popup verschijnen

**Comment by hans2103** [comment]
@hvdmeer werkt weer
![Schermafbeelding 2022-06-21 om 16 14 35](https://user-images.githubusercontent.com/639822/174821636-75a192e8-4252-4fcc-b5b1-632194fd4db4.png)
