### ISSUE TITLE
J!Version verouderd

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingjoomlanederland/joomlacommunity.nl#377]
Op de voorpagina staat een verwijzing naar de nieuwste download van Joomla.
Hier staat nog steeds Joomla 3.10 als verwijzing naar een download.
Ik heb ontdekt dat dit getoond wordt met de ooit door Niels gemaakte extensie J!Version.
Ik heb inmiddels de verwijzing aangepast naar de downloads van Joomla 4 maar in de module kan alleen maar naar versie 3 van Joomla worden verwezen, Joomla 4 ontbreekt.
Zou een techneut ervoor kunnen zorgen dat ook Joomla 4 in deze extensie mogelijk wordt?

**Comment by sanderpotjer** [comment]
@MartijnMaandag toont nu Joomla 4
