### ISSUE TITLE
[Homepage] Wijzigen nieuwste versie

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#381]
In het blok "Download" op de homepage staat dat versie 3.10.6 de nieuwste versie is. Voor de 3.x serie klopt dit maar kan hier de vermelding komen van Joomla 4.1.0 (op moment van indienen) de nieuwste versie is?

**Comment by MartijnMaandag** [comment]
Ik heb dit al eerder gemeld en gevraagd of een techneut hiernaar kan kijken: 
https://github.com/stichtingjoomlanederland/joomlacommunity.nl/issues/377

**Comment by hvdmeer** [comment]
Oeh, aan de hand van de titel had ik dit niet herkend
