### ISSUE TITLE
Wijzigingen opslaan in bedrijvengids 

### ISSUE THREAD

**Issue by Joomill** [stichtingjoomlanederland/joomlacommunity.nl#383]
Het is niet meer mogelijk om je pagina in de de bedrijvengids aan te passen.

Tijdens het opslaan: Uncaught TypeError: document.formvalidator is undefined

**Comment by hans2103** [comment]
De betreffende regel wordt wel degelijk aangeroepen.

https://github.com/stichtingjoomlanederland/joomlacommunity.nl/blob/2db1500d0628f6da9d57a157ed109c53a45898ca/public_html/templates/jc/html/com_content/form/edit.php#L18

**Comment by hans2103** [comment]
@MartijnMaandag en @Joomill met deze wijziging, een aanpassing in de configuratie van de systeem plugin httpdHeaders, activeren van de Joomla onzichtbare reCaptcha is het me gelukt een inzending te plaatsen. 
Ik sluit dit issue en verwijder mijn inzending
