### ISSUE TITLE
Afbeelding bij posts

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingjoomlanederland/joomlacommunity.nl#385]
Iemand meldt dat er maar één afbeelding per reactie geplaatst kan worden. Kan hier eens naar gekeken worden?

**Comment by hvdmeer** [comment]
In de instelling staat maximaal vier bestanden van elk max 2MB groot. Wellicht dat er een paar grote tussen zaten

**Comment by hans2103** [comment]
@MartijnMaandag ik heb denk ik het tegendeel bewezen
https://joomlacommunity.nl/forum/over-joomlacommunity-nl/pm-reageren-werkt-niet#reageer-24295

Maar... wat me opviel is dat als ik klik op de button _Upload Files_ het niet lukt om meerdere afbeeldingen tegelijkertijd te selecteren. Ik moet ze een voor een uploaden.
