### ISSUE TITLE
Login menu probleem 

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#396]
Het login menu item werkt niet in de desktop browser
![image](https://user-images.githubusercontent.com/7062995/175833053-06cff0ae-8aaa-4974-9b3b-0f99a6a78070.png)

**Comment by hans2103** [comment]
@hvdmeer issue opgelost met downgrade van Bootstrap van 5.x naar 3.4.1

![Schermafbeelding 2022-06-27 om 08 38 56](https://user-images.githubusercontent.com/639822/175875520-627057ac-d112-4406-900a-dee7128042ec.png)
