### ISSUE TITLE
Mobiel menu werkt niet

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#397]
Bij het benaderen van de website via een mobiel werkt het menu niet. Deze reageert niet op het "klikken" er op en klapt dus niet open.

**Comment by hans2103** [comment]
@hvdmeer issue opgelost met downgrade van Bootstrap van 5.x naar 3.4.1

![Schermafbeelding 2022-06-27 om 08 39 11](https://user-images.githubusercontent.com/639822/175875425-3ae7d175-deff-4870-b919-26ab847f876b.png)
