### ISSUE TITLE
[forum] reCaptcha probleempje - geen topics kunnen aanmaken

### ISSUE THREAD

**Issue by hvdmeer** [stichtingjoomlanederland/joomlacommunity.nl#399]
Normale gebruikers krijgen een foutmelding bij het willen aanmaken van een nieuw topic op het forum
![image](https://user-images.githubusercontent.com/7062995/176015156-a05940f4-daf9-40d2-8484-544faceb4ce4.png)

Met mijn verhoogde rechten heb ik daar (gelukkig) geen last van.

**Comment by hans2103** [comment]
reCaptha => in mijn poging spam registraties te voorkomen zaten we in ene met twee reCaptha
Eentje uitgeschakeld.. ik kan nu ook weer een user registreren. :-)


aanmaken nieuw topic is gelukt.
https://joomlacommunity.nl/forum/lounge/testing-issue-399
