### ISSUE TITLE
Front-end editing

### ISSUE THREAD

**Issue by n9iels** [stichtingjoomlanederland/joomlacommunity.nl#40]
Het zou handig zijn als alle artikelen zoals nieuws items, agenda's van gebruikersgroepen, downloads enz. geheel via de front-end bewerkt kunnen worden.
Hiervoor moet het volgende gebeuren:
- [x] ACL instellingen voor gebruikers
- Template aanpassen zodat front-end editing toegepast kan worden
  - [x] Override maken voor het bewerken van artikelen, deze moet compatible zijn met Bootstrap 3 en tegelijkertijd gebruikersvriendelijk
  - [x] Font-icons werken krijgen, momenteel worden icons als `icon-cog` gebruikt. Deze bestaan nu niet. Er moet dus een icon set komen hiervoor, of op een of andere manier het  goede icoontje worden ingeladen
  - [x] Mogelijkheid voor het toevoegen van nieuwe artikelen aan een categorie
  - [ ] Bewerken en toevoegen van downloads mogelijk maken
  - [x] RS!Events via de front-end aan kunnen passen

**Comment by n9iels** [comment]
Toegevoegd in 985a6231087df96680adf5ae05131e7d72c6c4b8

**Comment by n9iels** [comment]
De volgende dingen zijn toegevoegd:
- Override voor de front-end editing die gebruikersvriendelijker is dan de standaard
- Plugin die Bootstrap 2 elementen van Joomla! omzet naar Bootstrap 3
- Plugin die boven elke categorieblog een knop weergeeft om artikelen toe te voegen aan deze categorie. Deze knop is er enkel als de ingelogde gebruiker rechten heeft om artikelen aan te maken.

**Comment by n9iels** [comment]
Ik heb een plugin gemaakt die een button boven categorie lijsten en bloggen toevoegt. Deze button is een directe link voor het maken van een nieuw artikel in deze categorie.
Uiteraard wordt hierbij ook rekening gehouden met de ACL rechten van de huidige gebruiker :)
![image](https://cloud.githubusercontent.com/assets/2659866/17371691/1dfd5778-59a1-11e6-9c76-b9aee59484ae.png)

De plugin staat in een repository op mijn GitHub account, mocht  je hem zelf ook willen installeren:
https://github.com/n9iels/plg_system_newarticlebutton

**Comment by conconnl** [comment]
@n9iels 

**Downloads**
Bewerken en toevoegen van downloads is standaard een mogelijkheid bij RSFiles.
Ik weet alleen niet of dit stukje nog aanwezig is in de aangepaste view.
Ik denk als je de view bijwerkt en de toolbar er weer in zet het geregeld is.
/components/com_rsfiles/views/rsfiles/tmpl/default_navbar.php daar zou je moeten vinden wat je zoekt.

**Events**
RSEvents heeft standaard de mogelijkheid om evenementen te wijzigen.
Toevoegen van nieuwe is ook te regelen via een menu item.
Ik heb de site gecheckt en ik zie deze opties netjes staan bij de evenementen.

**Comment by n9iels** [comment]
@conconnl Bewerken van download in RSFiles lukt mij tot dusver niet. Snap simpelweg niet hoe het zou moeten werken ook met knop niet...

**Comment by conconnl** [comment]
Heb je de view al ge-update zodat de toolbar weer zichtbaar is?
Kun je die dan met mij delen, ik zie in de nieuwe view de toolbar niet meer en kan dit dus niet testen voor je en eventueel screenshots maken.

**Comment by n9iels** [comment]
Ik heb de issue voor versie 2.0 gezet. Ik denk dat dit namelijke niet iets is wat de live gang van de website hoeft tegen te houden :)

**Comment by allrude** [comment]
Frontend editing is inderdaad nog niet erg werkbaar, desktop versie moet inderdaad naar BS3.
Als je onder Afbeeldingen en links, op selecteren klikt ga je naar een fullscreen JCE filebrowser venster, wat vooral op mobiel niet geschikt is/werkt.

**Comment by sanderpotjer** [comment]
com_rsfiles is vervangen voor com_docman, frontend editing is daarvoor in ieder geval aanwezig en werkt. Uiteraard nog wel de events, content e.d. inrichten voor frontend editing, maar dat verder na livegang

**Comment by hans2103** [comment]
Geen frontend editing gewenst... Bewerken van items is een hele mooie administrator omgeving voor opgezet. Mochten meerdere groepen nodig zijn, dan kunnen deze via ACL aangemaakt worden.
